config/routes.rb
Edools::Application.routes.draw do

  constraints(Subdomain) do
    root to: 'schools#home', constraints: { format: /(html)/}

    resources :courses, :path => "curso", :only => [:show] do
      member do
        post 'request_certificate', path: 'solicitar_certificado'
        get 'add_to_cart', :path => "adicionar_ao_carrinho"
        get 'remove_from_cart', :path => "remover_do_carrinho"
        get 'content', :path => "conteudo" 
        post 'submit_message'
        post ':message_id/submit_answer' => "courses#submit_answer", as: :submit_answer
        delete ':message_id' => "courses#destroy_message", as: :destroy_message
        post ':cart_item_id/remove_coupon' => "courses#remove_coupon", as: :remove_coupon
        post ':cart_item_id/add_coupon' => "courses#add_coupon", as: :add_coupon
        get 'checkout_free', path: "matricule-se"
        get 'checkout_restrict', path: "restrito"
        get 'checkout_invitation/:user_email' => "courses#checkout_invitation", as: :checkout_invitation, path: "convite"
        post "create_lead"
        get 'coupon_sent', path: "cupom_enviado"
        get 'affiliate/:coupon' => "courses#affiliate", path: "afiliado/:coupon", as: :affiliate
      end
      resources :medias, only: [:show] do
        member do
          post :ended
        end
      end
    end     

    resources :schools, only: [] do
      member do
        get 'home'
      end
    end

    resources :checkouts, :path => '/checkout', :only => [] do
      collection do
        get 'cart', path: 'carrinho'
        post 'social', :path => "conecte-se"
        get 'social', :path => "conecte-se"
        get 'register', :path => "completar_cadastro"
        get 'payment', :path => "pagamento"
        get 'finish', :path => "sucesso"
        get 'finish_coupon', :path => "concluido"
        get 'failure', :path => "erro_pagamento"
        get 'finish_online_payment', :path => "sucesso_pagamento"
        get 'failure', :path => "erro_pagamento"
        get 'exception', :path => "overload"
        post 'pay_credit_card'
        post 'pay_online_debit'
        post 'pay_billet'
      end
    end   

    resources :purchases, :only => [:create] do
      collection do
        get "finances_billing_graphic"
        get "finances_billing_graphic_summary"
        get "affiliate_graphic"
      end
    end

    namespace :dashboard do 
      root :to => 'pages#index'
      
      resources :layout_configurations, :path => '/layout', only: [:index, :update]

      resources :courses do
        member do
          get 'library', path: 'biblioteca'
          get 'invite_students', path: 'convidar_alunos'
          get 'edit_links_downloads'
          get 'edit_basic_info'
          get 'edit_detailed_info'
          get 'edit_image'
          get 'edit_promo_video'
          get 'edit_available_time'
          get 'edit_instructor'
          post 'update_promo_video'
          get 'edit_privacy'
          get 'edit_teachers'
          get 'edit_price_and_coupon'
          get 'edit_certificate'
          post 'publish'
          post 'unpublish'
          get 'notifications'
          post 'create_lead'
        end
        collection do
          get 'leads'
          get "conversion_graphic"
          get 'index_teaching'
          get 'course_categories', path: "categorias"
          post 'sort_course_categories'
          put 'rename_course_category'
        end

        resources :lessons, :only => [:index] do
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :medias, only: [] do 
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :coupons
      end
      
      resources :schools, only: [:create, :update] do
        collection do
          get 'configurations_integrations', path: 'configuracoes/integracoes'
          get 'configurations_general', path: 'configuracoes/gerais'
          get 'configurations_plan', path: 'configuracoes/plano'
          get 'configurations_moip', path: 'configuracoes/moip'
          get 'configurations_domain', path: 'configuracoes/dominio'
          get 'configurations_notifications', path: 'configuracoes/notificacoes'
          get 'library', path: 'biblioteca'
          get 'team', path: 'equipe'
          get 'edit_basic_info', path: 'informacoes'
          get 'finances', path: 'financeiro'
          get 'conversions', path: 'conversoes'
          get 'course_evaluations', path: 'avaliacoes'
          get 'certificate'
          get 'coupons', path: 'cupons'
          get ':course/:student/certificate' => 'schools#show_certificate', as: :show_certificate, defaults: { format: "pdf" }
        end
      end
      
      resources :users, as: "students", path: "aluno", only: [:show, :index]
    end    
  end

  constraints(NotSubdomain) do
    root :to => "pages#index"

    namespace :admin do 
      root :to => 'pages#index'
      
      resources :pages, only: [] do
        collection do
          get :courses
          get :switch_to_school
        end
      end

      resources :feedbacks, :only => [:index]
      
      resources :features, only: [ :index ] do
        resources :feature_strategies, only: [ :update, :destroy ]
      end
    end

    namespace :dashboard do
      resources :schools, only: [:create, :update] do
        collection do
          get 'wizard_basic_info'
          get 'wizard_choose_plans'
        end
      end    
    end

    mount Flip::Engine => "/admin/features"

    match '/ensinar' => 'pages#teach', :as => :teach_page
    match '/aprender' => 'pages#learn', :as => :learn_page
    match '/planos' => 'pages#pricing', :as => :pricing_page
    match '/funcionalidades' => 'pages#features', :as => :features_page
  end

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }, :path => "usuarios"
  devise_scope :users do
    get 'perfil/pedidos' => 'users#purchases', :as => :purchases_user
    get 'perfil/editar' => 'users#edit_profile', :as => :edit_profile_user
    get 'perfil/mensagens' => 'users#messages', :as => :messages_user
    get 'dashboard/notifications' => 'users#notifications', as: :notifications_user, path: 'dashboard/notificacoes'
    post 'dashboard/mark_all_notifications_as_read' => 'users#mark_all_notifications_as_read', as: :mark_all_notifications_as_read_user
  end
  
  resources :pages, :only => [] do
    collection do
      post 'new_feedback'
    end
  end

  post 'moip/notification' => 'purchases#notification'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
	before_filter :authenticate_user!
	layout :layout_dashboard

	private
	def layout_dashboard
		"dashboard/dashboard"
	end
end

app/controllers/dashboard/coupons_controller.rb
#coding: utf-8

class Dashboard::CouponsController < Dashboard::BaseController
  load_and_authorize_resource
  before_filter :set_course
  
  # def update
  #   @coupon = @course.coupons.find(params[:id])
  #   if @coupon.update_attributes(params[:coupon])
  #     flash[:notice] = t("messages.coupon.update.success")
  #     redirect_to dashboard_coupons_path
  #   else
  #     flash[:alert] = @coupon.errors.full_messages
  #     render :edit
  #   end
  # end

  def create
    @coupon = @course.coupons.new(params[:coupon])
    if @coupon.save
      flash[:notice] = t("messages.coupon.create.success")
      redirect_to edit_price_and_coupon_dashboard_course_path(@course)
    else
      render template: "dashboard/courses/edit_price_and_coupon", layout: "dashboard/course_edit"
    end
  end

  def destroy
    @coupon = @course.coupons.find(params[:id])
    @coupon.destroy
    flash[:notice] = t("messages.coupon.destroy.success")
    redirect_to edit_price_and_coupon_dashboard_course_path(@course.id)
  end

  private
  def set_course
    @course = Course.find(params[:course_id])
  end

end

app/controllers/dashboard/layout_configurations_controller.rb
#coding: utf-8

class Dashboard::LayoutConfigurationsController < Dashboard::BaseController	
	load_and_authorize_resource

	def index
		@user = current_user
		@school = @user.school
		@layout = @school.layout_configuration 
	end

	def update
		@layout = LayoutConfiguration.find(params[:id])

		if @layout.update_attributes(params[:layout_configuration])
			flash[:notice] = t('messages.layout.update.success')
			redirect_to dashboard_layout_configurations_path
		else
			flash[:alert] = t('messages.layout.update.failure')
			render :index
		end	
	end

end

app/controllers/dashboard/lessons_controller.rb
#coding: utf-8

class Dashboard::LessonsController < Dashboard::BaseController
  layout :layout_course

  include Apotomo::Rails::ControllerMethods 
  has_widgets do |root|
    root << widget(:edit_curriculum)
  end

  def index
    @course = Course.find(params[:course_id])
    authorize! :dashboard_lessons_index, @course
  end

  def rename
    @course = Course.find(params[:course_id])
    @lesson = Lesson.find(params[:id])
    @lesson.update_attribute(:title, params[:lesson][:title]) if !params[:lesson][:title].blank?
    render :nothing => true

    authorize! :dashboard_lessons_rename, @course
  end

  def sort
    @course = Course.find(params[:course_id])
    @lesson = Lesson.find(params[:id])
    @lesson.update_attribute :sequence_position, params[:position]
    render nothing: true

    authorize! :dashboard_lessons_sort, @course
  end

  private
	def layout_course
		"dashboard/course_edit"
	end

end

app/controllers/dashboard/medias_controller.rb
#coding: utf-8

class Dashboard::MediasController < Dashboard::BaseController  
  def rename
    @course = current_user.courses.find(params[:course_id])
    @media = Media.find(params[:id])
    @media.update_attribute(:title, params[:media][:title]) if params[:media][:title].present?

    render :nothing => true
    authorize! :dashboard_medias_rename, @course
  end

  def sort
    @course = current_user.courses.find(params[:course_id])
    @lesson_media = LessonMedia.find(params[:id])
    @lesson_media.update_attribute :sequence_position, params[:position]
    
    render nothing: true
    authorize! :dashboard_medias_sort, @course
  end
end

app/controllers/dashboard/users_controller.rb
#coding: utf-8

class Dashboard::UsersController < Dashboard::BaseController  
  include Apotomo::Rails::ControllerMethods 
  has_widgets do |root|
    root << widget(:school_student_profile)
    root << widget(:school_students)
    root << widget(:progress)
  end

	def show
		@school = current_user.school
		@student = @school.students.find_by_id(params[:id])
    @page = params[:page]

    unless @student
      flash[:alert] = "Aluno não existe"
      redirect_to action: :index
    end
		
		authorize! :show, :dashboard_user
	end

	def index
		@school = current_user.school
    @students = @school.students.order(:first_name)

    authorize! :index, :dashboard_user

    respond_to do |format|
    	format.html
    	format.xls { send_data @students.to_csv(col_sep: "\t") }
    end
	end

end

app/helpers/layout_helper.rb
#coding: utf-8

module LayoutHelper

  def box(options = {}, &block)
    result = "".html_safe
    result << "<div class='box #{options[:class]}' id='#{options[:id]}' style='#{options[:style]}'>".html_safe
    if options[:title]
      result << '<div class="head"><h4>'.html_safe
      if options[:icon]
        result << "<i class=\"#{options[:icon]}\" style='opacity: 0.8;'></i>".html_safe
        result << "<span class='head-divider'></span>".html_safe
      end
      result << "#{options[:title]}".html_safe
      if options[:soon]
        result << " - <span class=\"soon hint hint--right\" data-hint=\"Ainda estamos finalizando essa funcionalidade, mas você já pode dar uma espiadinha ;-)\">Em breve! (?)</span>".html_safe
      end
      result << "</h4></div>".html_safe
    end
    result << "<div class='content' style='#{options[:content_style]}'>".html_safe
    result << capture(&block)
    result << '	</div></div>'.html_safe
  end

  def new_box(options = {}, &block)
    result = "".html_safe
    result << "<div class='new_box #{options[:class]}' id='#{options[:id]}'>".html_safe
    if options[:title]
      result << '<div class="new_head"><h2>'.html_safe
      if options[:icon]
        result << "<i class=\"#{options[:icon]}\"></i>".html_safe
      end
      result << "#{options[:title]}".html_safe
      if options[:soon]
        result << " - <span class=\"soon hint hint--right\" data-hint=\"Ainda estamos finalizando essa funcionalidade, mas você já pode dar uma espiadinha ;-)\">Em breve! (?)</span>".html_safe
      end
      result << "</h2></div>".html_safe
    end
    result << '<div class="new_content">'.html_safe
    result << capture(&block)
    result << ' </div></div>'.html_safe
  end  

end

app/views/layouts/dashboard/_course_menu.html.erb
<button id="course-menu-btn" class="btn expanded-btn" type="button">
  <i class="fa-icon-reorder"></i> <span>Menu</span>
</button>

<ul id="course-menu" class="nav nav-list">
	<li>
		<%= link_to_unless_current "Início", dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Início", dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>	

	<li class="nav-header"><h5>Conteúdo</h5></li>
	<li>
		<%= link_to_unless_current "Conteúdo", dashboard_course_lessons_path(@course) do %>
		<li class="active">
			<%= link_to "Conteúdo", dashboard_course_lessons_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Links e downloads", edit_links_downloads_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Links e downloads", edit_links_downloads_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>

  <li class="nav-header"><h5>Informações</h5></li>
	<li>
		<%= link_to_unless_current "Básicas", edit_basic_info_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Básicas", edit_basic_info_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Detalhadas", edit_detailed_info_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Detalhadas", edit_detailed_info_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Imagem", edit_image_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Imagem", edit_image_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Vídeo Promocional", edit_promo_video_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Vídeo Promocional", edit_promo_video_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Instrutor", edit_instructor_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Instrutor", edit_instructor_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>		

  <li class="nav-header"><h5>Configurações</h5></li>
	<li>
		<%= link_to_unless_current "Privacidade", edit_privacy_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Privacidade", edit_privacy_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Preço e Cupons", edit_price_and_coupon_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Preço e Cupons", edit_price_and_coupon_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Tempo disponível", edit_available_time_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Tempo disponível", edit_available_time_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>

	<li>
		<%= link_to_unless_current "Certificado", edit_certificate_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Certificado", edit_certificate_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>

	<li>
		<%#= link_to_unless_current "Professores", edit_teachers_dashboard_course_path(@course) do %>
		<!-- <li class="active"> -->
			<%#= link_to "Professores", edit_teachers_dashboard_course_path(@course) %>
		<!-- </li> -->
		<%# end -%>
	</li>

	<li class="nav-header"><h5>Mais</h5></li>
	<li>
		<%= link_to_unless_current "Convidar alunos", invite_students_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Convidar alunos", invite_students_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
	<li>
		<%= link_to_unless_current "Biblioteca de mídias", library_dashboard_course_path(@course) do %>
		<li class="active">
			<%= link_to "Biblioteca de mídias", library_dashboard_course_path(@course) %>
		</li>
		<% end -%>
	</li>
			
	<!-- <li>
		<%#= link_to_unless_current "Ajuda", '#' do %>
		<li class="active">
			<%#= link_to "Ajuda", '#' %>
		</li>
		<%# end -%>
	</li>				 -->
</ul>

<script type="text/javascript">
	$(document).ready(function() {
		$("#course-menu-btn").click(function (e){
			if($("#course-menu").is(":visible")) {
				$("#course-menu").slideUp({easing: "easeInOutBack"});
			} else {
				$("#course-menu").slideDown({easing: "easeInOutBack"});
			}
		});
	});
</script>		

app/views/layouts/dashboard/_footer.html.erb
<footer>
	<div class="container">
		<div class="row-fluid copyright">
            <div class="span2 pull-right">
                <p>2013 - Edools</p>
            </div>
        </div>
	</div>
</footer>

app/views/layouts/dashboard/_main_menu.html.erb
<div class="top-nav">
	<ul class="nav nav-tabs main-menu pagination-centered">

		<% if can? :edit_basic_info, School %>
			<%= nav_link edit_basic_info_dashboard_schools_path do %>
				<%= link_to edit_basic_info_dashboard_schools_path do %>
					<i class="fa-icon-info-sign"></i><br /><span class="hidden-tablet">Informações</span>
				<% end -%>
			<% end -%>
		<% end -%>
		
		<% if current_user.student? %>
			<%= nav_link dashboard_courses_path do %>
				<%= link_to dashboard_courses_path do %>
					<i class="fa-icon-facetime-video"></i><br /><span class="hidden-tablet">Cursos</span>
				<% end -%>
			<% end -%>
		<% else %>
			<%= nav_link dashboard_courses_path do %>
				<%= link_to dashboard_courses_path do %>
					<div class="nav-icon" data-menu-item="course">
						<i class="fa-icon-facetime-video"></i><span class="pull-right"><i class="fontello-icon-down-open-big"></i></span><br /><span class="hidden-tablet">Ensino</span>
					</div>
				<% end -%>
			<% end -%>
		<% end %>

		<% if can? :index, :dashboard_user %>		
			<%= nav_link dashboard_students_path do %>
				<%= link_to dashboard_students_path do %>
					<i class="fa-icon-group"></i><br /><span class="hidden-tablet">Pessoas</span>
				<% end -%>
			<% end -%>
		<% end %>
		
		<% if can? :finances, School %>
			<%= nav_link finances_dashboard_schools_path do %>
				<%= link_to finances_dashboard_schools_path do %>
					<i class="fa-icon-bar-chart"></i><br /><span class="hidden-tablet">Financeiro</span>
				<% end -%>
			<% end -%>
		<% end %>

		<% if can? :conversions, School %>
			<%= nav_link conversions_dashboard_schools_path do %>
				<%= link_to conversions_dashboard_schools_path do %>
					<div class="nav-icon" data-menu-item="conversions">
						<i class="fa-icon-filter"></i><span class="pull-right"><i class="fontello-icon-down-open-big"></i></span><br /><span class="hidden-tablet">Conversões</span>
					</div>
				<% end -%>
			<% end -%>
		<% end %>
	
		<% if can? :index, LayoutConfiguration %>
			<%= nav_link dashboard_layout_configurations_path do %>
				<%= link_to dashboard_layout_configurations_path do %>
					<i class="fa-icon-desktop"></i><br /><span class="hidden-tablet">Aparência</span>
				<% end -%>
			<% end -%>
		<% end %>

		<% if can? :configurations, School %>
			<%= nav_link configurations_general_dashboard_schools_path do %>
				<%= link_to configurations_general_dashboard_schools_path do %>
					<div class="nav-icon" data-menu-item="configurations">
						<i class="fa-icon-cogs"></i><span class="pull-right"><i class="fontello-icon-down-open-big"></i></span><br /><span class="hidden-tablet">Configurações</span>
					</div>
				<% end -%>
			<% end -%>
		<% end -%>

		<% if current_user.student? %>
			<%= nav_link messages_user_path do %>
				<%= link_to messages_user_path do %>
					<i class='icon-comment'></i><br /><span class="hidden-tablet">Contato</span>
				<% end -%>
			<% end -%>
		<% end -%>
														
	</ul>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('.nav-icon').click(function (e){
			if($(".sub-menu").is(":visible")) {
				$(".nav-icon").find(".pull-right").html("<i class='fontello-icon-down-open-big'></i>");
				$(".sub-menu").slideUp({easing: "easeInOutBack"});
				// $("*[data-menu-subitem=" + $(this).data("menu-item") + "]").slideUp({easing: "easeInOutBack"});
			} else {
				$(this).find(".pull-right").html("<i class='fontello-icon-up-open-big'></i>");
				$("*[data-menu-subitem=" + $(this).data("menu-item") + "]").slideDown({easing: "easeInOutBack"});
			}
			e.preventDefault();
		});
	});
</script>

app/views/layouts/dashboard/_sub_menu.html.erb
<div class="sub-menu" data-menu-subitem="course">
	<div class="row-fluid">
		<div class="span12">
			<div class="sub-nav"> 
				<div class="sub-nav-icon">
					<%= sub_nav_link dashboard_courses_path do %>
						<%= link_to dashboard_courses_path do %>
							<i class="fa-icon-th-large"></i><p>Cursos</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link library_dashboard_schools_path do %>
						<%= link_to library_dashboard_schools_path do %>
							<i class="fa-icon-hdd"></i><p>Biblioteca</p>
						<% end -%>
					<% end -%>
				</div>	

				<div class="sub-nav-icon">
					<%= sub_nav_link course_categories_dashboard_courses_path do %>
						<%= link_to course_categories_dashboard_courses_path do %>
							<i class="fa-icon-reorder"></i><p>Categorias</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link course_evaluations_dashboard_schools_path do %>
						<%= link_to course_evaluations_dashboard_schools_path do %>
							<i class="icon-ok-sign"></i><p>Avaliações</p>
						<% end -%>
					<% end -%>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="sub-menu" data-menu-subitem="conversions">
	<div class="row-fluid">
		<div class="span12">
			<div class="sub-nav"> 
				<div class="sub-nav-icon">
					<%= sub_nav_link conversions_dashboard_schools_path do %>
						<%= link_to conversions_dashboard_schools_path do %>
							<i class="fa-icon-filter"></i><p>Funís de Conversão</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link coupons_dashboard_schools_path do %>
						<%= link_to coupons_dashboard_schools_path do %>
							<i class="fa-icon-gift"></i><p>Cupons</p>
						<% end -%>
					<% end -%>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="sub-menu" data-menu-subitem="configurations">
	<div class="row-fluid">
		<div class="span12">
			<div class="sub-nav"> 
				<div class="sub-nav-icon">
					<%= sub_nav_link configurations_general_dashboard_schools_path do %>
						<%= link_to configurations_general_dashboard_schools_path do %>
							<i class="fa-icon-cog"></i><p>Geral</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link configurations_plan_dashboard_schools_path do %>
						<%= link_to configurations_plan_dashboard_schools_path do %>
							<i class="fa-icon-map-marker"></i><p>Plano</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link configurations_domain_dashboard_schools_path do %>
						<%= link_to configurations_domain_dashboard_schools_path do %>
							<i class="fa-icon-globe"></i><p>Domínio</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link configurations_moip_dashboard_schools_path do %>
						<%= link_to configurations_moip_dashboard_schools_path do %>
							<i class="fa-icon-money"></i><p>Conta MoIP</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link configurations_notifications_dashboard_schools_path do %>
						<%= link_to configurations_notifications_dashboard_schools_path do %>
							<i class="icon-bell"></i><p>Notificações</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link configurations_integrations_dashboard_schools_path do %>
						<%= link_to configurations_integrations_dashboard_schools_path do %>
							<i class="icon-random"></i><p>Integrações</p>
						<% end -%>
					<% end -%>
				</div>

			</div>
		</div>
	</div>
</div>

<div class="sub-menu" data-menu-subitem="people">
	<div class="row-fluid">
		<div class="span12">
			<div class="sub-nav"> 
				<div class="sub-nav-icon">
					<%= sub_nav_link dashboard_students_path do %>
						<%= link_to dashboard_students_path do %>
							<i class="fa-icon-group"></i><p>Alunos</p>
						<% end -%>
					<% end -%>
				</div>

				<div class="sub-nav-icon">
					<%= sub_nav_link team_dashboard_schools_path do %>
						<%= link_to team_dashboard_schools_path do %>
							<i class="fa-icon-user"></i><p>Equipe</p>
						<% end -%>
					<% end -%>
				</div>				

				<%# if current_school.cart_recovery %>
					<!-- <div class="sub-nav-icon">
						<%#= sub_nav_link leads_dashboard_courses_path do %>
							<%#= link_to leads_dashboard_courses_path do %>
								<i class="icon-shopping-cart"></i><p>Leads</p>
							<%# end -%>
						<%# end -%>
					</div>				 -->
				<%# end %>				
			</div>
		</div>
	</div>
</div>

app/views/layouts/dashboard/course_edit.html.erb
<%= content_for :course_edit_header do %>
  <%= render partial: 'layouts/dashboard/course_edit_header' %>
<% end %>

<%= content_for :course_edit_navigation do %>
  <%= render "layouts/dashboard/course_menu" %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/dashboard/create_school.html.erb
<%= render :template => 'layouts/application' %>

app/views/layouts/dashboard/dashboard.html.erb
<%= content_for :navigation do %>
  <%= render partial: 'layouts/dashboard/main_menu', locals: { active_item: 'edit' } %>
<% end %>

<%= content_for :dashboard_sub_menu do %>
  <%= render "layouts/dashboard/sub_menu" %>
<% end %>

<%= render :template => 'layouts/application' %>