config/routes.rb
Edools::Application.routes.draw do

  constraints(Subdomain) do
    root to: 'schools#home', constraints: { format: /(html)/}

    resources :courses, :path => "curso", :only => [:show] do
      member do
        post 'request_certificate', path: 'solicitar_certificado'
        get 'add_to_cart', :path => "adicionar_ao_carrinho"
        get 'remove_from_cart', :path => "remover_do_carrinho"
        get 'content', :path => "conteudo" 
        post 'submit_message'
        post ':message_id/submit_answer' => "courses#submit_answer", as: :submit_answer
        delete ':message_id' => "courses#destroy_message", as: :destroy_message
        post ':cart_item_id/remove_coupon' => "courses#remove_coupon", as: :remove_coupon
        post ':cart_item_id/add_coupon' => "courses#add_coupon", as: :add_coupon
        get 'checkout_free', path: "matricule-se"
        get 'checkout_restrict', path: "restrito"
        get 'checkout_invitation/:user_email' => "courses#checkout_invitation", as: :checkout_invitation, path: "convite"
        post "create_lead"
        get 'coupon_sent', path: "cupom_enviado"
        get 'affiliate/:coupon' => "courses#affiliate", path: "afiliado/:coupon", as: :affiliate
      end
      resources :medias, only: [:show] do
        member do
          post :ended
        end
      end
    end     

    resources :schools, only: [] do
      member do
        get 'home'
      end
    end

    resources :checkouts, :path => '/checkout', :only => [] do
      collection do
        get 'cart', path: 'carrinho'
        post 'social', :path => "conecte-se"
        get 'social', :path => "conecte-se"
        get 'register', :path => "completar_cadastro"
        get 'payment', :path => "pagamento"
        get 'finish', :path => "sucesso"
        get 'finish_coupon', :path => "concluido"
        get 'failure', :path => "erro_pagamento"
        get 'finish_online_payment', :path => "sucesso_pagamento"
        get 'failure', :path => "erro_pagamento"
        get 'exception', :path => "overload"
        post 'pay_credit_card'
        post 'pay_online_debit'
        post 'pay_billet'
      end
    end   

    resources :purchases, :only => [:create] do
      collection do
        get "finances_billing_graphic"
        get "finances_billing_graphic_summary"
        get "affiliate_graphic"
      end
    end

    namespace :dashboard do 
      root :to => 'pages#index'
      
      resources :layout_configurations, :path => '/layout', only: [:index, :update]

      resources :courses do
        member do
          get 'library', path: 'biblioteca'
          get 'invite_students', path: 'convidar_alunos'
          get 'edit_links_downloads'
          get 'edit_basic_info'
          get 'edit_detailed_info'
          get 'edit_image'
          get 'edit_promo_video'
          get 'edit_available_time'
          get 'edit_instructor'
          post 'update_promo_video'
          get 'edit_privacy'
          get 'edit_teachers'
          get 'edit_price_and_coupon'
          get 'edit_certificate'
          post 'publish'
          post 'unpublish'
          get 'notifications'
          post 'create_lead'
        end
        collection do
          get 'leads'
          get "conversion_graphic"
          get 'index_teaching'
          get 'course_categories', path: "categorias"
          post 'sort_course_categories'
          put 'rename_course_category'
        end

        resources :lessons, :only => [:index] do
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :medias, only: [] do 
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :coupons
      end
      
      resources :schools, only: [:create, :update] do
        collection do
          get 'configurations_integrations', path: 'configuracoes/integracoes'
          get 'configurations_general', path: 'configuracoes/gerais'
          get 'configurations_plan', path: 'configuracoes/plano'
          get 'configurations_moip', path: 'configuracoes/moip'
          get 'configurations_domain', path: 'configuracoes/dominio'
          get 'configurations_notifications', path: 'configuracoes/notificacoes'
          get 'library', path: 'biblioteca'
          get 'team', path: 'equipe'
          get 'edit_basic_info', path: 'informacoes'
          get 'finances', path: 'financeiro'
          get 'conversions', path: 'conversoes'
          get 'course_evaluations', path: 'avaliacoes'
          get 'certificate'
          get 'coupons', path: 'cupons'
          get ':course/:student/certificate' => 'schools#show_certificate', as: :show_certificate, defaults: { format: "pdf" }
        end
      end
      
      resources :users, as: "students", path: "aluno", only: [:show, :index]
    end    
  end

  constraints(NotSubdomain) do
    root :to => "pages#index"

    namespace :admin do 
      root :to => 'pages#index'
      
      resources :pages, only: [] do
        collection do
          get :courses
          get :switch_to_school
        end
      end

      resources :feedbacks, :only => [:index]
      
      resources :features, only: [ :index ] do
        resources :feature_strategies, only: [ :update, :destroy ]
      end
    end

    namespace :dashboard do
      resources :schools, only: [:create, :update] do
        collection do
          get 'wizard_basic_info'
          get 'wizard_choose_plans'
        end
      end    
    end

    mount Flip::Engine => "/admin/features"

    match '/ensinar' => 'pages#teach', :as => :teach_page
    match '/aprender' => 'pages#learn', :as => :learn_page
    match '/planos' => 'pages#pricing', :as => :pricing_page
    match '/funcionalidades' => 'pages#features', :as => :features_page
  end

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }, :path => "usuarios"
  devise_scope :users do
    get 'perfil/pedidos' => 'users#purchases', :as => :purchases_user
    get 'perfil/editar' => 'users#edit_profile', :as => :edit_profile_user
    get 'perfil/mensagens' => 'users#messages', :as => :messages_user
    get 'dashboard/notifications' => 'users#notifications', as: :notifications_user, path: 'dashboard/notificacoes'
    post 'dashboard/mark_all_notifications_as_read' => 'users#mark_all_notifications_as_read', as: :mark_all_notifications_as_read_user
  end
  
  resources :pages, :only => [] do
    collection do
      post 'new_feedback'
    end
  end

  post 'moip/notification' => 'purchases#notification'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

end

app/controllers/checkouts_controller.rb
#coding: utf-8

class CheckoutsController < ApplicationController
	before_filter :authenticate_user!, except: [:cart, :social]
	load_and_authorize_resource class: :checkout
	
	include Apotomo::Rails::ControllerMethods	
  has_widgets do |root|
    root << widget(:secure_info)
    root << widget(:school_phone_email)
    root << widget(:school_payment_forms)
  end
	
	def cart
	end

	def social
		if current_cart
			@user = User.new
			redirect_to :action => :register if user_signed_in?
		else
			redirect_to root_path(subdomain: current_school.subdomain)
		end
	end

	def register
		if current_cart || params[:purchase_id]
			@user = current_user
			@user.build_address if @user.address.nil?
		else
			redirect_to root_path(subdomain: current_school.subdomain)
		end
	end

	def payment
		if params[:purchase_id]
			@purchase = Purchase.find_by_id(params[:purchase_id])
			@installments = @purchase.maximum_installments
		elsif current_cart.present? && current_cart.token.present?
			@cart = current_cart
			@installments = @cart.maximum_installments
		elsif current_user.purchases.any?
			@purchase = current_user.purchases.last
			@installments = @purchase.maximum_installments
		else
			flash[:alert] = I18n.t("messages.checkout_moip.failure")
			redirect_to root_path(subdomain: current_school.subdomain) and return
		end
	end

	def failure
		@message = params[:message]
	end

	def finish
		@purchase = current_user.purchases.last
		
		unless @purchase
			redirect_to root_path(subdomain: current_school.subdomain) 
		end

		@message = params[:message]
		@courses = @purchase.courses
	end

	def finish_online_payment
		@purchase = current_user.purchases.last
		
		unless @purchase
			redirect_to root_path(subdomain: current_school.subdomain) 
		end

		@url = MyMoip.api_url + "/Instrucao.do?token=#{@purchase.token}"
	end

	def finish_coupon
		@purchase = current_user.purchases.last

		unless @purchase
			redirect_to root_path(subdomain: current_school.subdomain) 
		end
	end

	def pay_credit_card	
		find_purchase

		unless @purchase.present? && @token.present?
			flash[:alert] = I18n.t("messages.checkout_moip.failure")
			redirect_to root_path(subdomain: current_school.subdomain) and return
		end

		credit_card = build_credit_card
		
		unless credit_card.valid?
			flash[:purchase_message] = "Cartão de crédito inválido"
			SupportMailer.payment_credit_card_failure(@purchase, credit_card).deliver
			redirect_to failure_checkouts_path and return
		end

		credit_card_payment = MyMoip::CreditCardPayment.new(credit_card, installments: params[:payment][:installments])
		payment_request = MyMoip::PaymentRequest.new("zangrandii@gmail.com")
		payment_request.api_call(credit_card_payment, token: @token)

		unless payment_request.response["Status"] != "Cancelado"
			flash[:purchase_message] = "Cartão de crédito inválido"
			redirect_to failure_checkouts_path and return
		end
		
		unless payment_request.success?
			flash[:purchase_message] = payment_request.response["Mensagem"]
			redirect_to failure_checkouts_path and return
		end

		payment_request.response["Forma"] = "CartaoCredito"
		update_purchase_attributes(payment_request.response)

		if current_school.automatic_confirmation
			@purchase.payment_status = Purchase::LIBERATED
		end

		if @purchase.save
			session[:cart_id] = nil if current_cart && session[:cart_id] == current_cart.id
			current_cart.destroy if current_cart
			if current_school.automatic_confirmation
				@purchase.register_on_rdstation "liberado"
				@purchase.create_liberated_notification
			else
				@purchase.register_on_rdstation "pendente"
				@purchase.create_pending_notification
			end
			redirect_to finish_checkouts_path
		else
			flash[:purchase_message] = "Erro ao gerar compra"
			redirect_to failure_checkouts_path
		end
	end

	def pay_online_debit
		find_purchase

		unless @purchase.present? && @token.present?
			flash[:alert] = I18n.t("messages.checkout_moip.failure")
			redirect_to root_path(subdomain: current_school.subdomain) and return
		end

		online_payment = OnlinePayment.new("DebitoBancario", institution: params[:payment][:institution])

		payment_request = MyMoip::PaymentRequest.new("zangrandii@gmail.com")
		payment_request.api_call(online_payment, token: @token)

		# payment_request.response["StatusPagamento"] = "Falha"
		
		unless payment_request.success?
			flash[:purchase_message] = payment_request.response["Mensagem"]
			redirect_to failure_checkouts_path and return
		end

		payment_request.response["Forma"] = "DebitoBancario"
		update_purchase_attributes(payment_request.response)

		if @purchase.save
			session[:cart_id] = nil if current_cart && session[:cart_id] == current_cart.id
			current_cart.destroy if current_cart
			@purchase.register_on_rdstation "pendente"
			@purchase.create_pending_notification
			redirect_to finish_online_payment_checkouts_path
		else
			flash[:purchase_message] = "Erro ao gerar compra"
			redirect_to failure_checkouts_path
		end
	end

	def pay_billet
		find_purchase

		unless @purchase.present? && @token.present?
			flash[:alert] = I18n.t("messages.checkout_moip.failure")
			redirect_to root_path(subdomain: current_school.subdomain) and return
		end

		online_payment = OnlinePayment.new("BoletoBancario")
		payment_request = MyMoip::PaymentRequest.new("zangrandii@gmail.com")
		payment_request.api_call(online_payment, token: @token)

		unless payment_request.success?
			flash[:purchase_message] = payment_request.response["Mensagem"]
			redirect_to failure_checkouts_path and return
		end

		payment_request.response["Forma"] = "BoletoBancario"
		update_purchase_attributes(payment_request.response)

		if @purchase.save
			session[:cart_id] = nil if current_cart && session[:cart_id] == current_cart.id
			current_cart.destroy if current_cart
			@purchase.register_on_rdstation "pendente"
			@purchase.create_pending_notification
			redirect_to finish_online_payment_checkouts_path
		else
			flash[:purchase_message] = "Erro ao gerar compra"
			redirect_to failure_checkouts_path
		end
	end	

	private
	def update_purchase_attributes response
		@purchase.payment_status = response["Status"] if response["Status"].present?
		@purchase.payment_type = response["Forma"] if response["Forma"].present?
		@purchase.moip_tax = response["TaxaMoIP"] if response["TaxaMoIP"].present?
		@purchase.moip_code = response["CodigoMoIP"] if response["CodigoMoIP"].present?
		if Rails.env.production? && response["TotalPago"].present?
			@purchase.amount_paid = response["TotalPago"]
		elsif response["TotalPago"].present?
			@purchase.amount_paid = (response["TotalPago"].to_f * 100).to_i
		end
	end

	def find_purchase
		if params[:purchase_id]
			@purchase = Purchase.find_by_id(params[:purchase_id])
			@token = @purchase.token
		elsif current_cart.present? && current_cart.token.present?
			@purchase = current_user.purchases.build(
				cart_items: current_cart.cart_items,
	      identificator: current_cart.identificator,
	      token: current_cart.token,
	      payment_status: "Iniciado"
			)
			@token = current_cart.token
		elsif current_user.purchases.any?
			@purchase = current_user.purchases.last
			@token = @purchase.token
		end
	end

	def build_credit_card
		MyMoip::CreditCard.new(
		  logo: params[:payment][:credit_card].try(:downcase),
		  card_number: params[:payment][:credit_card_number],
		  expiration_date: "#{params[:payment][:expiration_month]}/#{params[:payment][:expiration_year]}",
		  security_code: params[:payment][:credit_card_security_code],
		  owner_name: current_user.full_name,
		  owner_birthday: "03/11/1984",
		  owner_phone: current_user.phone_number,
		  owner_cpf: current_user.cpf.to_s
		)
	end

	def use_https?
		if current_school.try(:use_custom_domain)
		  ["pay_credit_card", "payment", "pay_online_debit", "pay_billet"].include?(params[:action])
		else
			!request.host.include?("lvh.me") && !Rails.env.staging?
		end
  end
end

app/helpers/checkout_helper.rb
#coding: utf-8

module CheckoutHelper

	def calculate_installments value, installments
    result = []
    moip_taxes.first(installments.to_i).each_with_index do |c, i|
      i += 1
      tax_message = i == 1 ? "s/ juros" : "c/ juros"
      value_with_tax = (value * c).round(2)
      installment = (value_with_tax / i).round(2)
      if i == 1
        result << ["#{i}x de #{em_real(installment)} #{tax_message}", i]
      else
        result << ["#{i}x de #{em_real(installment)} #{tax_message} (#{em_real(value_with_tax)})", i]
      end
    end
    result
  end

  def max_installments_value total
    em_real((total * moip_taxes[installments_amount(total) - 1]) / installments_amount(total).round(2))
  end

  def installments_amount total
    result = total / 500.0
    if result >= 12
      12
    elsif result.to_i == 0
      1
    else
      result.to_i
    end 
  end

  def moip_taxes
  	[1, 1.0299, 1.0401, 1.0502, 
     1.0605, 1.07076, 1.08122, 
     1.0917, 1.10214, 1.1126, 
     1.12332, 1.134]
  end

end

app/views/checkouts/_cart_header.html.erb
<br>
<div class="row-fluid">
	<div class="span12">
		<h1><i class="icon-shopping-cart"></i> Carrinho de Compras</h1>
	</div>
</div>
<hr class="black">

app/views/checkouts/_cart_item.html.erb
<% course = cart_item.course %>

<div class="box_widget_course">
	<div class="box">
		<div class="head">
			<div class="row-fluid">
				<div class="span11">
					<h4><%= link_to course.title, course_path(course), :id => "course-in-cart-#{course.slug}" %></h4>
				</div>
				<div class="span1">
					<div class="pull-right delete_cart_item">
						<%= link_to "<i class=\"fa-icon-trash\"></i>".html_safe, remove_from_cart_course_path(course.id), :id => "remove-course-#{course.slug}" %>
					</div>
				</div>
			</div>
		</div>
		<div class="content">
			<% if flash["invalid_coupon_#{cart_item.id}"] %>
				<div class="row-fluid">
					<div class="span12">
					  <p class="app-alert"><%= flash["invalid_coupon_#{cart_item.id}"] %></p>
					</div>
				</div>
		  <% end %>
		  <div class="row-fluid">
				<div class="span5">
					<%= image_tag course.logo.url(:medium), class: "thumbnail" %>
				</div>
				<div class="span7">
					<p class=""><%= course.pitch %></p>
					<% if course.limited? %>
						<small>* disponível durante <%= course.available_time %> dias após confirmação da compra</small>
					<% end %>
					<hr>
					<p>
						<div class="row-fluid">
							<div class="span4">
								<h3><strong><%= em_real cart_item.price_with_discount %></strong></h3>	
							</div>
							
							<% unless cart_item.coupon %>
								<div class="span8" style="margin-top: 5px;">
									<%= form_tag add_coupon_course_path(course, cart_item) do %>
										<div class="row-fluid">
											<div class="span8">
												<%= text_field_tag :coupon, nil, :placeholder => "Cupom de desconto", :maxlength => 20, :class => 'span12 form-control', "data-validate" => "validate(required(cupom)) on(submit)", :id => "cart-coupon-course-#{course.id}" %>
											</div>
											<div class="span1">
												<%= submit_tag "OK", :class => "btn-success btn", :id => "refresh-coupon-#{course.id}" %>	
											</div>
										</div>
									<% end -%>
								</div>
							<% else %>
								<div class="span8" style="margin-top: 5px;">
									<div class="row-fluid">
										<div class="span8">
											<p class="uneditable-input"><%= cart_item.coupon.name %></p>
										</div>
										<div class="span1">
											<p><%= link_to "x", remove_coupon_course_path(course, cart_item), :method => :post, :id => "remove-coupon-#{course.id}", :class => "btn-warning btn" %></p>
										</div>
									</div>
								</div>
							<% end %>
						</div>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/checkouts/_cart_item_purchased.html.erb
<% course = cart_item.course %>

<div class="box_widget_course">
	<div class="box">
		<div class="head">
			<div class="pull-left">
				<h4><%= link_to course.title, course_path(course), :id => "course-in-cart-#{course.slug}" %></h4>
			</div>
		</div>
		<div class="content">
			<% if flash["invalid_coupon_#{cart_item.id}"] %>
				<div class="row-fluid">
					<div class="span7">
					  <p class="app-alert"><%= flash["invalid_coupon_#{cart_item.id}"] %></p>
					</div>
				</div>
		  <% end %>
		  <div class="row-fluid">
				<div class="span5">
					<%= image_tag course.logo.url(:medium), class: "thumbnail" %>
				</div>
				<div class="span7">
					<p class=""><%= course.pitch %></p>
					<p>
						<div class="row-fluid">
							<div class="span4 well">
								<h3><%= em_real cart_item.price_with_discount %></h3>	
							</div>
							
							<% if cart_item.coupon %>
								<div class="span2"><p class="uneditable-input"><%= cart_item.coupon.name %></p></div>
							<% end %>
						</div>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/checkouts/_form_billet.html.erb
<%= form_tag pay_billet_checkouts_path do %>	
	<% if @purchase.present? %>
		<%= hidden_field_tag :purchase_id, @purchase.id %>
	<% end %>
	
	<p class="flag-panel">
		<label class="checkbox inline flag boleto">
			<%= radio_button_tag "payment[form]", "Billet", true, :name => "payment_billet" %>
		</label>
	</p>

	<p class="app-alert">Desabilite o bloqueio de pop-ups do seu navegador</p>
	<hr>
	<div class="transaction-actions">
		<%= link_to "← voltar", register_checkouts_path %>
		<%= submit_tag "Efetuar pagamento", :class => "btn btn-success btn-large pull-right btn-process-transaction", :id => "comprar-curso-boleto-bancario" %>
	</div>
	<div class="process-transaction">
	</div>
	<div class="transaction-message">
		<p><strong>Processando sua transação. Por favor, aguarde.</strong></p>
	</div>
<% end -%>

app/views/checkouts/_form_credit_card.html.erb
<%= form_tag pay_credit_card_checkouts_path(purchase_id: @purchase.try(:id)) do %>
	<% if @purchase.present? %>
		<%= hidden_field_tag :purchase_id, @purchase.id %>
	<% end %>

	<div class="row-fluid">
		<div class="span7">
			<div id="credit-card-form" class="register-form large-label">
				<p class="flag-panel" id="credit-card-logos">
					<label class="checkbox inline flag mastercard">
						<%= radio_button_tag "payment[credit_card]", "Mastercard", false %>
					</label>

					<label class="checkbox inline flag visa">
						<%= radio_button_tag "payment[credit_card]", "Visa", false %>
					</label>

					<label class="checkbox inline flag amex">
						<%= radio_button_tag "payment[credit_card]", "American_Express", false %>
					</label>

					<label class="checkbox inline flag diners">
						<%= radio_button_tag "payment[credit_card]", "Diners", false %>
					</label>

					<label class="checkbox inline flag hipercard">
						<%= radio_button_tag "payment[credit_card]", "Hipercard", false %>
					</label>
				</p>
				<hr>

				<p><%= label_tag "payment[credit_card_number]", "Nº do Cartão de Crédito" %>
					<%= text_field_tag "payment[credit_card_number]", nil %></p>

				<p><%= label_tag "payment[credit_card_security_code]", "Cód. de Segurança" %>
					<%= text_field_tag "payment[credit_card_security_code]", nil, :maxlength => 4 %></p>

				<p>
					<%= label_tag "payment[expiration_month]", "Validade (mês/ano)" %>
					<%= select_tag "payment[expiration_month]", options_for_select(("01".."12")), :include_blank => true %> /
					<%= select_tag "payment[expiration_year]", options_for_select((13..25)), :include_blank => true %>
				</p>

				<p>
					<%= label_tag "payment[installments]", "Parcelas" %>
					<%= select_tag "payment[installments]", options_for_select(calculate_installments(@purchase.try(:total) || @cart.try(:total), @installments)) %>
				</p>
			</div>

		</div>
	</div>

	<hr>
	
	<div class="transaction-actions">
		<%= link_to "← voltar", register_checkouts_path %>
		<%= submit_tag "Efetuar pagamento", :class => "btn btn-success btn-large pull-right btn-process-transaction", :id => "comprar-curso-cartao-credito" %>
	</div>
	<div class="process-transaction">
	</div>							
	<div class="transaction-message">
		<p><strong>Processando sua transação. Por favor, aguarde.</strong></p>
	</div>					
<% end %>

<script type="text/javascript">
	$(document).ready(function() {
		$('#comprar-curso-cartao-credito').attr('disabled', 'disabled');

		$('#credit-card-logos input:radio, #payment_credit_card_number, #payment_credit_card_security_code, #payment_expiration_month, #payment_expiration_year').bind("change propertychange keyup input paste", function () {
			if($("#credit-card-logos input:radio:checked").val() && $("#payment_credit_card_number").val() && 
					$("#payment_credit_card_security_code").val() && $("#payment_expiration_month").val() && 
					$("#payment_expiration_year").val()) {
				$('#comprar-curso-cartao-credito').removeAttr('disabled');
			} else {
				$('#comprar-curso-cartao-credito').attr('disabled', 'disabled');
			}
		});
	});

</script>

app/views/checkouts/_form_online_debit.html.erb
<%= form_tag pay_online_debit_checkouts_path do %>
	<% if @purchase.present? %>
		<%= hidden_field_tag :purchase_id, @purchase.id %>
	<% end %>

	<p class="flag-panel" id="online-debit-institutions">
		<label class="checkbox inline flag bank-banco-do-brasil">
			<%= radio_button_tag "payment[institution]", "BancoDoBrasil", false %>
		</label>

		<label class="checkbox inline flag bank-bradesco">
			<%= radio_button_tag "payment[institution]", "Bradesco", false %>
		</label>

		<label class="checkbox inline flag bank-itau">
			<%= radio_button_tag "payment[institution]", "Itau", false %>
		</label>
	</p>

	<p class="app-alert">Desabilite o bloqueio de pop-ups do seu navegador</p>
	<hr>
	<div class="transaction-actions">
		<%= link_to "← voltar", register_checkouts_path %>
		<%= submit_tag "Efetuar pagamento", :class => "btn btn-success btn-large pull-right btn-process-transaction", :id => "comprar-curso-debito-online" %>
	</div>
	<div class="process-transaction">
	</div>
	<div class="transaction-message">
		<p><strong>Processando sua transação. Por favor, aguarde.</strong></p>
	</div>

<% end -%>


<script type="text/javascript">

	$(document).ready(function() {
		$('#comprar-curso-debito-online').attr('disabled', 'disabled');

		$('#online-debit-institutions input:radio').bind("change propertychange keyup input paste", function () {
			checked = $("#online-debit-institutions input:radio:checked").val();
			if(checked) {
				$('#comprar-curso-debito-online').removeAttr('disabled');
			} else {
				$('#comprar-curso-debito-online').attr('disabled', 'disabled');
			}
		});
	});
</script>

app/views/checkouts/_order.html.erb
<% order = @purchase || current_cart %>

<% if order.present? %>
	<div id="purchase">	
		<%= box(:title => "Seu Pedido")  do %>	
			<% order.cart_items.each_with_index do |cart_item, i| %>
				<% course = cart_item.course %>
				<p><strong><%= link_to course.title, course_path(course) %></strong></p>
				<p><%= em_real cart_item.price_with_discount %></p>
			<% end -%>
			<% if order.is_a?(Purchase) && order.fee > 0 %>
				<p><strong>Taxa parcelamento</strong></p>
				<p><%= em_real order.fee %></p>
				<div class="footer-content">
					<h3><strong>Total: <%= em_real order.total_with_fee %></strong></h3>
				</div>
			<% else %>
				<div class="footer-content">
					<h3><strong>Total: <%= em_real order.total %></strong></h3>
				</div>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/checkouts/cart.html.erb
<div id="cart">
	<div class="container">
		<%= render 'checkouts/cart_header' %>
		
		<div class="row-fluid">
			<% if current_cart && current_cart.courses.any? %>
				<div class="span8">
					<% current_cart.cart_items.each do |cart_item| %>
						<%= render 'cart_item', :cart_item => cart_item %>
					<% end -%>
				</div>

				<div class="span4">
					<%= box(:title => 'Total')  do %>
						<h3>
							Total
							<strong class="pull-right"><%= em_real current_cart.total %></strong>
						</h3>
						<h4>
							ou em até <%= installments_amount current_cart.total %>x no cartão
							<strong class="pull-right"><%= max_installments_value(current_cart.total) %></strong>
						</h4>
						<hr>
						<%= link_to "Finalizar Compra →", social_checkouts_path, :class => "btn btn-success btn-large pull-right", :id => "checkout" %>
					<% end %>

					<%= render_widget :school_payment_forms, :display %>
					<%= render_widget :school_phone_email, :checkout, :school => current_school  %>
					<%= render_widget :secure_info %>
				</div>
			<% else %>
				<div class="span12">
					<%= box(title: "Oops!") do %>
						<h4><%= I18n.t("messages.cart.no_courses") %></h4>
					<% end %>
				</div>
			<% end -%>
		</div>
	</div>
</div>