config/routes.rb
Edools::Application.routes.draw do

  constraints(Subdomain) do
    root to: 'schools#home', constraints: { format: /(html)/}

    resources :courses, :path => "curso", :only => [:show] do
      member do
        post 'request_certificate', path: 'solicitar_certificado'
        get 'add_to_cart', :path => "adicionar_ao_carrinho"
        get 'remove_from_cart', :path => "remover_do_carrinho"
        get 'content', :path => "conteudo" 
        post 'submit_message'
        post ':message_id/submit_answer' => "courses#submit_answer", as: :submit_answer
        delete ':message_id' => "courses#destroy_message", as: :destroy_message
        post ':cart_item_id/remove_coupon' => "courses#remove_coupon", as: :remove_coupon
        post ':cart_item_id/add_coupon' => "courses#add_coupon", as: :add_coupon
        get 'checkout_free', path: "matricule-se"
        get 'checkout_restrict', path: "restrito"
        get 'checkout_invitation/:user_email' => "courses#checkout_invitation", as: :checkout_invitation, path: "convite"
        post "create_lead"
        get 'coupon_sent', path: "cupom_enviado"
        get 'affiliate/:coupon' => "courses#affiliate", path: "afiliado/:coupon", as: :affiliate
      end
      resources :medias, only: [:show] do
        member do
          post :ended
        end
      end
    end     

    resources :schools, only: [] do
      member do
        get 'home'
      end
    end

    resources :checkouts, :path => '/checkout', :only => [] do
      collection do
        get 'cart', path: 'carrinho'
        post 'social', :path => "conecte-se"
        get 'social', :path => "conecte-se"
        get 'register', :path => "completar_cadastro"
        get 'payment', :path => "pagamento"
        get 'finish', :path => "sucesso"
        get 'finish_coupon', :path => "concluido"
        get 'failure', :path => "erro_pagamento"
        get 'finish_online_payment', :path => "sucesso_pagamento"
        get 'failure', :path => "erro_pagamento"
        get 'exception', :path => "overload"
        post 'pay_credit_card'
        post 'pay_online_debit'
        post 'pay_billet'
      end
    end   

    resources :purchases, :only => [:create] do
      collection do
        get "finances_billing_graphic"
        get "finances_billing_graphic_summary"
        get "affiliate_graphic"
      end
    end

    namespace :dashboard do 
      root :to => 'pages#index'
      
      resources :layout_configurations, :path => '/layout', only: [:index, :update]

      resources :courses do
        member do
          get 'library', path: 'biblioteca'
          get 'invite_students', path: 'convidar_alunos'
          get 'edit_links_downloads'
          get 'edit_basic_info'
          get 'edit_detailed_info'
          get 'edit_image'
          get 'edit_promo_video'
          get 'edit_available_time'
          get 'edit_instructor'
          post 'update_promo_video'
          get 'edit_privacy'
          get 'edit_teachers'
          get 'edit_price_and_coupon'
          get 'edit_certificate'
          post 'publish'
          post 'unpublish'
          get 'notifications'
          post 'create_lead'
        end
        collection do
          get 'leads'
          get "conversion_graphic"
          get 'index_teaching'
          get 'course_categories', path: "categorias"
          post 'sort_course_categories'
          put 'rename_course_category'
        end

        resources :lessons, :only => [:index] do
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :medias, only: [] do 
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :coupons
      end
      
      resources :schools, only: [:create, :update] do
        collection do
          get 'configurations_integrations', path: 'configuracoes/integracoes'
          get 'configurations_general', path: 'configuracoes/gerais'
          get 'configurations_plan', path: 'configuracoes/plano'
          get 'configurations_moip', path: 'configuracoes/moip'
          get 'configurations_domain', path: 'configuracoes/dominio'
          get 'configurations_notifications', path: 'configuracoes/notificacoes'
          get 'library', path: 'biblioteca'
          get 'team', path: 'equipe'
          get 'edit_basic_info', path: 'informacoes'
          get 'finances', path: 'financeiro'
          get 'conversions', path: 'conversoes'
          get 'course_evaluations', path: 'avaliacoes'
          get 'certificate'
          get 'coupons', path: 'cupons'
          get ':course/:student/certificate' => 'schools#show_certificate', as: :show_certificate, defaults: { format: "pdf" }
        end
      end
      
      resources :users, as: "students", path: "aluno", only: [:show, :index]
    end    
  end

  constraints(NotSubdomain) do
    root :to => "pages#index"

    namespace :admin do 
      root :to => 'pages#index'
      
      resources :pages, only: [] do
        collection do
          get :courses
          get :switch_to_school
        end
      end

      resources :feedbacks, :only => [:index]
      
      resources :features, only: [ :index ] do
        resources :feature_strategies, only: [ :update, :destroy ]
      end
    end

    namespace :dashboard do
      resources :schools, only: [:create, :update] do
        collection do
          get 'wizard_basic_info'
          get 'wizard_choose_plans'
        end
      end    
    end

    mount Flip::Engine => "/admin/features"

    match '/ensinar' => 'pages#teach', :as => :teach_page
    match '/aprender' => 'pages#learn', :as => :learn_page
    match '/planos' => 'pages#pricing', :as => :pricing_page
    match '/funcionalidades' => 'pages#features', :as => :features_page
  end

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }, :path => "usuarios"
  devise_scope :users do
    get 'perfil/pedidos' => 'users#purchases', :as => :purchases_user
    get 'perfil/editar' => 'users#edit_profile', :as => :edit_profile_user
    get 'perfil/mensagens' => 'users#messages', :as => :messages_user
    get 'dashboard/notifications' => 'users#notifications', as: :notifications_user, path: 'dashboard/notificacoes'
    post 'dashboard/mark_all_notifications_as_read' => 'users#mark_all_notifications_as_read', as: :mark_all_notifications_as_read_user
  end
  
  resources :pages, :only => [] do
    collection do
      post 'new_feedback'
    end
  end

  post 'moip/notification' => 'purchases#notification'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

end

app/controllers/courses_controller.rb
#coding: utf-8

class CoursesController < ApplicationController			
	require 'securerandom'

	load_and_authorize_resource
	skip_authorize_resource :only => :render_event_response # To work with apotomo

	include Apotomo::Rails::ControllerMethods	
	has_widgets do |root|
		root << widget(:school_phone_email)
		root << widget(:course_alumni)
		root << widget(:course_school)
    root << widget(:downloads)
    root << widget(:progress)
    root << widget(:questions)
    root << widget(:curriculum)
    root << widget(:course_testimonials)
    root << widget(:about)
    root << widget(:course_faq)
    root << widget(:how_it_works)
    root << widget(:how_to_enroll)
    root << widget(:who_should_attend)
    root << widget(:content_and_goals)
    root << widget(:course_evaluation)
    root << widget(:course_advantages)
    root << widget(:school_payment_forms)
    root << widget(:course_instructor)
    root << widget(:course_cart_recovery)
  end
	
	def show  
	  @course = Course.find(params[:id])
	  @school = @course.school
		@title = @course.title
		@coupon = @course.coupons.find_by_name(params[:coupon]) if params[:coupon]
		@path = if @course.restrict?
			checkout_restrict_course_path(@course)
		elsif @course.free?
			checkout_free_course_path(@course)
		elsif @coupon
			add_to_cart_course_path(@course, coupon: @coupon.name)
		elsif current_school.try(:cart_recovery) && !user_signed_in?
			"#newLead"
		else
			add_to_cart_course_path(@course)
		end

		Notification.create(
			code: Notification::COURSE_VIEW_PAGE, 
			notifiable: @course,
			personal: true
		)
	end

	def content
		@course = Course.find(params[:id])
		@medias = @course.medias.order(:sequence)
		@messages = @course.questions.order("created_at DESC").page(params[:page]).per(6)

    Notification.create(
      sender: current_user,
      code: Notification::USER_VIEW_COURSE_CONTENT,
      notifiable: @course,
      personal: true
    )
	end

	def checkout_free
		@course = Course.find(params[:id])
		@school = @course.school

		unless @course.free?
			redirect_to root_path(subdomain: @school.subdomain), alert: "Esse curso não é gratuito." and return
		end

		if user_signed_in?
			@course.students_invited << current_user
			redirect_to content_course_path(@course)
		end

		@user = User.new
	end

	def checkout_invitation
		@course = Course.find(params[:id])
		@school = @course.school

		@invitation = @course.invitations.find_by_email(params[:user_email])

		unless @invitation
			redirect_to root_path(subdomain: @school.subdomain), alert: "Convite inválido." and return
		end

		if user_signed_in? && current_user.email == @invitation.email
			current_user.courses_invited << @course unless current_user.courses_invited.include?(@course)
			@invitation.destroy
			redirect_to content_course_path(@course)
		elsif user_signed_in?
			flash[:alert] = "Você não pode usar esse convite."
			redirect_to request.referer || root_path(subdomain: @school.subdomain) and return
		end

		@user = User.new
	end

	def checkout_restrict
		@course = Course.find(params[:id])
		@school = @course.school

		if user_signed_in?
			redirect_to add_to_cart_course_path(@course)
		else
			@user = User.new
		end
	end

	def add_to_cart
		@course = Course.find(params[:id])
		@cart = Cart.find_by_id(session[:cart_id]) || Cart.create
		
		if @cart.courses.include? @course
			flash[:alert] = t("messages.course.add_to_cart.already_in_cart")
			redirect_to cart_checkouts_path(subdomain: current_subdomain) and return
		end
		
		if @course.draft?
			flash[:alert] = t("messages.course.add_to_cart.invalid")
			redirect_to root_path(subdomain: current_subdomain) and return
		end

		if user_signed_in? && @course.restrict? && !@course.array_of_allowed_emails.include?(current_user.email)
			flash[:alert] = t("messages.course.add_to_cart.restrict")
			redirect_to root_path(subdomain: current_subdomain) and return
		end

		if params[:coupon]
			@coupon = @course.coupons.active.find_by_name(params[:coupon])
			flash[:alert] = t("messages.course.add_to_cart.invalid_coupon") unless @coupon
		end

		@cart.cart_items.build course: @course, coupon: @coupon

		if @cart.save
	    Notification.create_list(
	    	sender: current_user, 
				receivers: current_school.team, 
				code: Notification::COURSE_ADD_TO_CART, 
				notifiable: @course
			) if current_school && current_user
			session[:cart_id] = @cart.id
			redirect_to cart_checkouts_path(subdomain: current_subdomain)
		end
	end

	def remove_from_cart
		@course = Course.find(params[:id])

		if @course && current_cart
			cart_item = CartItem.find_by_cart_id_and_course_id(current_cart.id, @course.id)
			cart_item.destroy if cart_item
			redirect_to cart_checkouts_path
		else
			redirect_to root_url, :alert => I18n.t("messages.course.remove_from_cart.failure")
		end
	end

	def add_coupon
		@course = Course.find(params[:id])
		@cart_item = CartItem.find(params[:cart_item_id])
		@coupon = @course.coupons.active.find_by_name(params[:coupon])

		if @coupon
			if @cart_item.update_attributes(coupon: @coupon)
				flash[:notice] = t("messages.course.add_coupon.success")
			else
				flash[:alert] = t("messages.course.add_coupon.failure")
			end
		else
			flash["invalid_coupon_#{@cart_item.id}"] = t("coupon.invalid")
		end

		redirect_to cart_checkouts_path
	end

	def remove_coupon
		@course = Course.find(params[:id])
		@cart_item = CartItem.find(params[:cart_item_id])
		@cart_item.update_attribute(:coupon_id, nil)
		flash[:notice] = t("messages.course.remove_coupon.success")
		redirect_to cart_checkouts_path		
	end	

	def request_certificate
		@course = Course.find(params[:id])

		begin
			Notification.create_list(
				sender: current_user, 
				receivers: @course.school.admins + @course.teachers, 
				notifiable: @course, 
				code: Notification::COURSE_NEW_CERTIFICATE_REQUEST
			)
			flash[:notice] = "Solicitação de certificado enviada com sucesso"
		rescue
			flash[:alert] = "Ocorreu um erro ao solicitar seu certificado"
		end

		redirect_to content_course_path(@course)
	end

	def affiliate
		@course = Course.find(params[:id])
		@coupon = @course.coupons.find_by_name(params[:coupon])

		unless @coupon
			flash[:alert] = "Cupom não encontrado."
			redirect_to root_path(subdomain: current_school.subdomain) and return
		end

		@cart_items = CartItem.with_purchase.with_price.where(coupon_id: @coupon.id).includes(:purchase).order("cart_items.created_at DESC")
		@cart_items_confirmed = @cart_items.payment_confirmed
		
		@billing_last_month = @cart_items_confirmed.between((Date.today - 1.month).beginning_of_month, (Date.today - 1.month).end_of_month).sum(&:price_with_discount)
    @billing_this_month = @cart_items_confirmed.between(Date.today.beginning_of_month, Date.today).sum(&:price_with_discount)

    @total_of_cart_items_confirmed = @cart_items_confirmed.length
    @total_of_cart_items_pending = @cart_items.pending.length
    @total_of_cart_items_canceled = @cart_items.canceled.length
    @total_of_cart_items_paid_with_billet = @cart_items_confirmed.paid_with_billet.length
    @total_of_cart_items_paid_with_online_debit = @cart_items_confirmed.paid_with_online_debit.length
    @total_of_cart_items_paid_with_credit_card = @cart_items_confirmed.paid_with_credit_card.length

		@cart_items = @cart_items.page(params[:page]).per(20)
	end

	private
	def use_https?
		unless current_school.try(:use_custom_domain) || request.host.include?("lvh.me") || Rails.env.staging?
			["add_coupon", "remove_coupon", "remove_from_cart", "checkout_free"].include?(params[:action])
		end
  end

end

app/helpers/courses_helper.rb
#coding: utf-8

module CoursesHelper

	def payment_status_message course_item
		case course_item.status
		when :within_validity
			"<i class=\"icon-facetime-video\"></i> Assistir Curso".html_safe
		when :pending
			"<i class=\"icon-time\"></i> Pagamento #{course_item.purchase.payment_status}".html_safe
		when :out_of_date
			"<i class=\"icon-ban-circle\"></i> Período terminado".html_safe
		end
	end

	def payment_status_path course_item
		case course_item.status
		when :within_validity
			content_course_path(course_item.course)
		when :pending
			purchases_user_path
		when :out_of_date
			course_path(course_item.course)
		end
	end

	def payment_status_availabity_message course_item
		case course_item.status
		when :within_validity
			if course_item.limited?
				"Disponível até #{I18n.l(course_item.expires_at, format: :medium)}"
			else
				"Disponível indeterminadamente"
			end
		when :pending
			"Pagamento #{course_item.purchase.payment_status}"
		when :out_of_date
			"Período terminado em #{I18n.l(course_item.expires_at, format: :medium)}"
		end
	end

end

app/views/courses/_course_box.html.erb
<div class="span3" id="course-box-<%= course.id %>">
	<div class="course-item-home thumbnail" onclick=" window.location = '<%= course_path(course) %>'">
		<div class="img-container">
			<%= image_tag(course.logo.url(:medium)) %>
		</div>
		<div class="title_pitch">
			<h3 class="title">
				<span><%= course.title %></span>
			</h3>
			<h4 class="pitch">
				<span><%= course.pitch %></span>
			</h4>
		</div>
		<hr>
		<div class="clearfix"></div>
			<div class="course_price well">
				<% if @school.pricing_style_full? || course.free? %>
					<%= em_real course.price %>
				<% else %>
					<%= installments_amount course.price %>x
					<span><%= max_installments_value(course.price) %></span>
				<% end %>
			</div>
			<div class="order">
				<% if course.restrict? %>
					<% path = checkout_restrict_course_path(course) %>
				<% elsif course.free? %>
					<% path = checkout_free_course_path(course) %>
				<% else %>
					<% path = add_to_cart_course_path(course) %>
				<% end %>
				
				<%= link_to t("course.buy"), path, :class => "btn btn-success", :id => "course-buy-#{course.slug}" %>
			</div>
		<div class='clearfix'></div>
	</div>
</div>

app/views/courses/affiliate.html.erb
<br>


<div class="container">
  <!-- <hr class="black"> -->

  <div class="row-fluid">
    <div class="pretty_box">
      <div class="row-fluid">
        <div class="span2">
          <%= image_tag @course.logo.url(:medium), style: "width: 100%;" %>
        </div>
        <div class="span9">
          <h1><i class="fontello-icon-chart-line"></i> Relatório de Vendas</h1>
          <hr>
          <h2><%= @course.title %></h2>
          <h5><%= @coupon.name %></h5>
        </div>
      </div>
    </div>
  </div>
</div>
	
<div id="course_content">
	<div class="container">
		<div id="course-id" data-course-id="<%= @course.id %>">
		<div id="coupon-name" data-coupon-name="<%= @coupon.name %>">

		<%= box(:title => "Faturamento", :icon => "fa-icon-bar-chart")  do %>
			<div class="row-fluid" id="finances-summary">
				<div class="offset2 span4 pagination-centered">
					<div class="well">
						<h2><%= em_real_with_zero @billing_last_month %></h2> 
						Faturamento do mês anterior
					</div>
				</div>
				<div class="span4 pagination-centered">
					<div class="well">
						<h2><%= em_real_with_zero @billing_this_month %></h2> 
						Faturamento do mês atual
					</div>
				</div>
			</div>

			<div class="row-fluid">
				<div id="container_highchart_summary"></div>
			</div>
		<% end %>

    <%= box(:title => "Detalhado", icon: "fa-icon-money")  do %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Curso</th>
            <th>Unidades vendidas</th>
            <th>Total bruto</th>
            <th>Taxa Moip</th>
            <th>Total líquido</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to @course.title, @course %></td>
            <td><%= @cart_items_confirmed.length %></td>
            <td><%= @cart_items_confirmed.sum(&:price_with_discount).em_real %></td>
            <td><%= @cart_items_confirmed.sum { |ci| ci.moip_tax * 100 }.em_real %></td>
            <td><%= @cart_items_confirmed.sum { |ci| ci.price_with_discount - (ci.moip_tax * 100) }.em_real %></td>
          </tr>
        </tbody>
      </table>
    <% end %>

		<%= box(:title => "Extrato", :icon => "fa-icon-list")  do %>
      <div class="row-fluid">
        <div class="span3">
          <h4>Confirmadas: <%= @total_of_cart_items_confirmed %></h4>
          <h4>Pendentes: <%= @total_of_cart_items_pending %></h4>
          <h4>Canceladas: <%= @total_of_cart_items_canceled %></h4>
        </div>
        <div class="span3">
          <% if @total_of_cart_items_confirmed > 0 %>
            <h4>Cartão de crédito: <%= @total_of_cart_items_paid_with_credit_card %> (<%= ((@total_of_cart_items_paid_with_credit_card.to_f / @total_of_cart_items_confirmed) * 100).to_i %>%)</h4>
            <h4>Débito online: <%= @total_of_cart_items_paid_with_online_debit %> (<%= ((@total_of_cart_items_paid_with_online_debit.to_f / @total_of_cart_items_confirmed) * 100).to_i %>%)</h4>
            <h4>Boleto bancário: <%= @total_of_cart_items_paid_with_billet %> (<%= ((@total_of_cart_items_paid_with_billet.to_f / @total_of_cart_items_confirmed) * 100).to_i %>%)</h4>
          <% end %>
        </div>
        <div class="span6">
          <div class="pull-right small-font align-right">
            <p><%= link_to "<i class='icon-download-alt'></i> Exportar".html_safe, dashboard_students_path(format: "xls") %>
          </div>
        </div>
      </div>
		  <hr>
			<table class="table table-striped">
				<thead>
        	<tr>
            <th>Aluno</th>
            <th>Data</th>
            <th>Valor</th>
            <th>Status</th>
            <th>Forma de Pagamento</th>
          </tr>
        </thead>
        <tbody>
        	<% @cart_items.each do |cart_item| %>
            <% purchase = cart_item.purchase %>
          	<tr>
              <td><%= purchase.user.full_name %></td>
              <td><%= l purchase.created_at, format: :medium %></td>
              <td><%= em_real_with_zero cart_item.price_with_discount %></td>
              <td><%= purchase.payment_status %></td>
              <td><%= purchase.payment_type %></td>
            </tr>
        	<% end %>
        </tbody>
      </table>
      <div class="apple_pagination" style="font-size: 14px;">
        <%= paginate @cart_items %>
      </div>
   	<% end %>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
    function affiliate_graphic(){
      course_id = $("#course-id").data("course-id");
      coupon_name = $("#coupon-name").data("coupon-name");
      $.ajax({
        url: "/purchases/affiliate_graphic" + "?course_id=" + course_id + "&coupon_name=" + encodeURIComponent(coupon_name),
        dataType: "json",
        success: function(graphicData){
          splineGraphic("container_highchart_summary", "", graphicData.categories, graphicData.data, 'spline');
        }
      });
    }

		affiliate_graphic();
	});
</script>

app/views/courses/show.html.erb
<%= content_for :title do %>
	<%= @course.title %> | <%= @school.name %>
<% end %>

<%#= content_for :modal do %>

	<div id="newLead" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="margin-right: 3px;">×</button>
  	<%= render_widget :course_cart_recovery, :display, course: @course %>
	</div>

<%# end %>

<%= content_for :opengraph do %>
	<script type="text/javascript" src="//w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">stLight.options({publisher: "b15c5521-c9f6-4fe6-aa2b-c616db09a138", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

	<meta property="og:title" content="<%= @course.title %>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="<%= course_url(@course) %>" />
	<meta property="og:image" content="<%= @course.logo.url(:large) %>" />
	<meta property="og:description" content="<%= @course.pitch %>" />
	<meta property="og:site_name" content="<%= @school.name %>" />
	<meta property="og:locale" content="pt_br" />
<% end %>

<div id="course_banner" class="course_top_bar">
	<div class="container">
    <div class="row-fluid animated fadeInUp">
			<div class="span5 pagination-centered picture">
				<div class="row-fluid">
						<% if @course.video_url? %>
							<div class="span12">
								<iframe width="100%" height="270" src="//www.youtube.com/embed/<%= @course.video_url %>?autoplay=0&autohide=1" frameborder="0" allowfullscreen></iframe>
							</div>
						<% else %>
							<div class="shadow img-polaroid span12 img-container">
								<%= image_tag @course.logo.url(:large), :class=>"" %>
							</div>					
						<% end %>
				</div>
			</div>
			<div class="span7 pagination-centered">

				<h1><%= @course.title %></h1>
				<h2><%= @course.pitch %></h2>	
				<div class="btn-buy">
					<!-- <div class="payment-info payment-info-top">
					</div> -->
					<%= link_to @path, :class => "multi-line-button green", :id => "course-buy-#{@course.slug}", "role" => "button", "data-toggle" => "modal" do %>
						<span class="title">
							<span><%= t("course.buy") %></span>
						</span>
						<span class="subtitle">
							<span class="badge badge-white">
								<h4>
									<% if current_school.try(:pricing_style_full?) || @course.free? %>
										<%= em_real @course.price %>
									<% else %>
										<%= installments_amount @course.price %>x
										<span><%= max_installments_value(@course.price) %></span>
									<% end %>
								</h4>
							</span>
						</span>
					<% end %>
					<% if @course.restrict? %>
						<h5 id="course-price-at-sight">
							Este curso é restrito apenas para convidados.
						</h5>
					<% elsif @course.paid? %>
						<% if current_school.try(:pricing_style_full?) %>
							<h5 id="course-price-at-sight">
								ou em <%= installments_amount @course.price %>x de <span><%= max_installments_value(@course.price) %></span>
								<% if @course.limited? %>
								  | curso disponível por <%= @course.available_time %> dias   
								<% end %>
							</h5>
						<% else %>
							<h5 id="course-price-at-sight">
								ou <%= em_real @course.price_with_discount(@coupon) %> à vista
								<% if @course.limited? %>
									| curso disponível por <%= @course.available_time %> dias    
								<% end %>
							</h5>
						<% end %>
					<% end %>
				</div>
			</div>		
		</div>
	</div>
</div>
	
<div id="course_content">
	<div class="container">
    	<div class="row-fluid">
    		<div class="span1">
    			<span class='st_facebook_vcount' displayText='Facebook'></span>
					<span class='st_twitter_vcount' displayText='Tweet' st_title='<%= @course.pitch %>' st_via='<%= @school.twitter || "edools_" %>'></span>
					<span class='st_googleplus_vcount' displayText='g+'></span>
					<span class='st_pinterest_vcount' displayText='Pinterest'></span>
    		</div>
      	<div class="span7" id="course_description">
    			<div class="pretty_box">
	      		<h3>
	      			por <span class="roman"><%= link_to @school.name.upcase, root_path(subdomain: @school.subdomain) %></span>
	      			<% if @course.certificate_available? %>
		      			<p class="badge pull-right muted" style="margin-left: 8px;">
		      				<i class="icon-edit" style="font-size: 12px; color: white; "> com certificado</i>
		      			</p>
		      		<% end %>

	      			<p class="badge pull-right muted" style="margin-left: 8px;">
	      				<i class="icon-time" style="font-size: 12px; color: white; "> 
	      					disponível 24h
	      					<% if @course.limited? %>
	      						durante <%= @course.time_available %> dias
	      					<% end %>
	      				</i>
	      			</p>
	      		</h3>
	      		<hr>
						<span class="description">
							<% unless @course.description.nil? %>
								<%= sanitize @course.description.gsub(/font-size:(.*);/, "font-size:16px;") %>
							<% end %>
						</span>
					</div>
					<%= render_widget :curriculum, :sales_page, course: @course %>
				</div>
	      <div class="span4 sidebar">
	      	<%= render_widget :course_advantages, :display, course: @course %>
	      	<% unless @course.free? %>
		      	<%= render_widget :school_payment_forms, :display %>
		      <% end %>
					<%= render_widget :school_phone_email, :course, :school => @school %>
					<%= render_widget :content_and_goals, :display, :course => @course %>
					<%= render_widget :who_should_attend, :display, :course => @course %>
					<%= render_widget :course_testimonials, :display, :course => @course %>
	      	<%= render_widget :course_instructor, :display, :course => @course %>
	      	<%= render_widget :course_school, :display, :course => @course %>

	      	<%= render_widget :course_alumni, :display, :course => @course %>
	      	<%= render_widget :course_evaluation, :show, :course => @course %>
					<%#= render_widget :about, :display, :course => @course %>
					<%#= render_widget :how_to_enroll %>
					<%= render_widget :course_faq, :display, course: @course %>
	     	</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

	$(document).ready(function() {
		$('#submit-lead').attr('disabled', 'disabled');

		$('#lead_email').bind("change propertychange keyup input paste", function () {
			email = $(this).val();
			filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if(filter.test(email)) {
				$('#submit-lead').removeAttr('disabled');
			} else {
				$('#submit-lead').attr('disabled', 'disabled');
			}
		});
	});
</script>