config/routes.rb
Edools::Application.routes.draw do

  constraints(Subdomain) do
    root to: 'schools#home', constraints: { format: /(html)/}

    resources :courses, :path => "curso", :only => [:show] do
      member do
        post 'request_certificate', path: 'solicitar_certificado'
        get 'add_to_cart', :path => "adicionar_ao_carrinho"
        get 'remove_from_cart', :path => "remover_do_carrinho"
        get 'content', :path => "conteudo" 
        post 'submit_message'
        post ':message_id/submit_answer' => "courses#submit_answer", as: :submit_answer
        delete ':message_id' => "courses#destroy_message", as: :destroy_message
        post ':cart_item_id/remove_coupon' => "courses#remove_coupon", as: :remove_coupon
        post ':cart_item_id/add_coupon' => "courses#add_coupon", as: :add_coupon
        get 'checkout_free', path: "matricule-se"
        get 'checkout_restrict', path: "restrito"
        get 'checkout_invitation/:user_email' => "courses#checkout_invitation", as: :checkout_invitation, path: "convite"
        post "create_lead"
        get 'coupon_sent', path: "cupom_enviado"
        get 'affiliate/:coupon' => "courses#affiliate", path: "afiliado/:coupon", as: :affiliate
      end
      resources :medias, only: [:show] do
        member do
          post :ended
        end
      end
    end     

    resources :schools, only: [] do
      member do
        get 'home'
      end
    end

    resources :checkouts, :path => '/checkout', :only => [] do
      collection do
        get 'cart', path: 'carrinho'
        post 'social', :path => "conecte-se"
        get 'social', :path => "conecte-se"
        get 'register', :path => "completar_cadastro"
        get 'payment', :path => "pagamento"
        get 'finish', :path => "sucesso"
        get 'finish_coupon', :path => "concluido"
        get 'failure', :path => "erro_pagamento"
        get 'finish_online_payment', :path => "sucesso_pagamento"
        get 'failure', :path => "erro_pagamento"
        get 'exception', :path => "overload"
        post 'pay_credit_card'
        post 'pay_online_debit'
        post 'pay_billet'
      end
    end   

    resources :purchases, :only => [:create] do
      collection do
        get "finances_billing_graphic"
        get "finances_billing_graphic_summary"
        get "affiliate_graphic"
      end
    end

    namespace :dashboard do 
      root :to => 'pages#index'
      
      resources :layout_configurations, :path => '/layout', only: [:index, :update]

      resources :courses do
        member do
          get 'library', path: 'biblioteca'
          get 'invite_students', path: 'convidar_alunos'
          get 'edit_links_downloads'
          get 'edit_basic_info'
          get 'edit_detailed_info'
          get 'edit_image'
          get 'edit_promo_video'
          get 'edit_available_time'
          get 'edit_instructor'
          post 'update_promo_video'
          get 'edit_privacy'
          get 'edit_teachers'
          get 'edit_price_and_coupon'
          get 'edit_certificate'
          post 'publish'
          post 'unpublish'
          get 'notifications'
          post 'create_lead'
        end
        collection do
          get 'leads'
          get "conversion_graphic"
          get 'index_teaching'
          get 'course_categories', path: "categorias"
          post 'sort_course_categories'
          put 'rename_course_category'
        end

        resources :lessons, :only => [:index] do
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :medias, only: [] do 
          member do
            put 'rename'
          end

          collection do
            post 'sort'
          end
        end
        resources :coupons
      end
      
      resources :schools, only: [:create, :update] do
        collection do
          get 'configurations_integrations', path: 'configuracoes/integracoes'
          get 'configurations_general', path: 'configuracoes/gerais'
          get 'configurations_plan', path: 'configuracoes/plano'
          get 'configurations_moip', path: 'configuracoes/moip'
          get 'configurations_domain', path: 'configuracoes/dominio'
          get 'configurations_notifications', path: 'configuracoes/notificacoes'
          get 'library', path: 'biblioteca'
          get 'team', path: 'equipe'
          get 'edit_basic_info', path: 'informacoes'
          get 'finances', path: 'financeiro'
          get 'conversions', path: 'conversoes'
          get 'course_evaluations', path: 'avaliacoes'
          get 'certificate'
          get 'coupons', path: 'cupons'
          get ':course/:student/certificate' => 'schools#show_certificate', as: :show_certificate, defaults: { format: "pdf" }
        end
      end
      
      resources :users, as: "students", path: "aluno", only: [:show, :index]
    end    
  end

  constraints(NotSubdomain) do
    root :to => "pages#index"

    namespace :admin do 
      root :to => 'pages#index'
      
      resources :pages, only: [] do
        collection do
          get :courses
          get :switch_to_school
        end
      end

      resources :feedbacks, :only => [:index]
      
      resources :features, only: [ :index ] do
        resources :feature_strategies, only: [ :update, :destroy ]
      end
    end

    namespace :dashboard do
      resources :schools, only: [:create, :update] do
        collection do
          get 'wizard_basic_info'
          get 'wizard_choose_plans'
        end
      end    
    end

    mount Flip::Engine => "/admin/features"

    match '/ensinar' => 'pages#teach', :as => :teach_page
    match '/aprender' => 'pages#learn', :as => :learn_page
    match '/planos' => 'pages#pricing', :as => :pricing_page
    match '/funcionalidades' => 'pages#features', :as => :features_page
  end

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }, :path => "usuarios"
  devise_scope :users do
    get 'perfil/pedidos' => 'users#purchases', :as => :purchases_user
    get 'perfil/editar' => 'users#edit_profile', :as => :edit_profile_user
    get 'perfil/mensagens' => 'users#messages', :as => :messages_user
    get 'dashboard/notifications' => 'users#notifications', as: :notifications_user, path: 'dashboard/notificacoes'
    post 'dashboard/mark_all_notifications_as_read' => 'users#mark_all_notifications_as_read', as: :mark_all_notifications_as_read_user
  end
  
  resources :pages, :only => [] do
    collection do
      post 'new_feedback'
    end
  end

  post 'moip/notification' => 'purchases#notification'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

end

app/controllers/courses_controller.rb
#coding: utf-8

class CoursesController < ApplicationController			
	require 'securerandom'

	load_and_authorize_resource
	skip_authorize_resource :only => :render_event_response # To work with apotomo

	include Apotomo::Rails::ControllerMethods	
	has_widgets do |root|
		root << widget(:school_phone_email)
		root << widget(:course_alumni)
		root << widget(:course_school)
    root << widget(:downloads)
    root << widget(:progress)
    root << widget(:questions)
    root << widget(:curriculum)
    root << widget(:course_testimonials)
    root << widget(:about)
    root << widget(:course_faq)
    root << widget(:how_it_works)
    root << widget(:how_to_enroll)
    root << widget(:who_should_attend)
    root << widget(:content_and_goals)
    root << widget(:course_evaluation)
    root << widget(:course_advantages)
    root << widget(:school_payment_forms)
    root << widget(:course_instructor)
    root << widget(:course_cart_recovery)
  end
	
	def show  
	  @course = Course.find(params[:id])
	  @school = @course.school
		@title = @course.title
		@coupon = @course.coupons.find_by_name(params[:coupon]) if params[:coupon]
		@path = if @course.restrict?
			checkout_restrict_course_path(@course)
		elsif @course.free?
			checkout_free_course_path(@course)
		elsif @coupon
			add_to_cart_course_path(@course, coupon: @coupon.name)
		elsif current_school.try(:cart_recovery) && !user_signed_in?
			"#newLead"
		else
			add_to_cart_course_path(@course)
		end

		Notification.create(
			code: Notification::COURSE_VIEW_PAGE, 
			notifiable: @course,
			personal: true
		)
	end

	def content
		@course = Course.find(params[:id])
		@medias = @course.medias.order(:sequence)
		@messages = @course.questions.order("created_at DESC").page(params[:page]).per(6)

    Notification.create(
      sender: current_user,
      code: Notification::USER_VIEW_COURSE_CONTENT,
      notifiable: @course,
      personal: true
    )
	end

	def checkout_free
		@course = Course.find(params[:id])
		@school = @course.school

		unless @course.free?
			redirect_to root_path(subdomain: @school.subdomain), alert: "Esse curso não é gratuito." and return
		end

		if user_signed_in?
			@course.students_invited << current_user
			redirect_to content_course_path(@course)
		end

		@user = User.new
	end

	def checkout_invitation
		@course = Course.find(params[:id])
		@school = @course.school

		@invitation = @course.invitations.find_by_email(params[:user_email])

		unless @invitation
			redirect_to root_path(subdomain: @school.subdomain), alert: "Convite inválido." and return
		end

		if user_signed_in? && current_user.email == @invitation.email
			current_user.courses_invited << @course unless current_user.courses_invited.include?(@course)
			@invitation.destroy
			redirect_to content_course_path(@course)
		elsif user_signed_in?
			flash[:alert] = "Você não pode usar esse convite."
			redirect_to request.referer || root_path(subdomain: @school.subdomain) and return
		end

		@user = User.new
	end

	def checkout_restrict
		@course = Course.find(params[:id])
		@school = @course.school

		if user_signed_in?
			redirect_to add_to_cart_course_path(@course)
		else
			@user = User.new
		end
	end

	def add_to_cart
		@course = Course.find(params[:id])
		@cart = Cart.find_by_id(session[:cart_id]) || Cart.create
		
		if @cart.courses.include? @course
			flash[:alert] = t("messages.course.add_to_cart.already_in_cart")
			redirect_to cart_checkouts_path(subdomain: current_subdomain) and return
		end
		
		if @course.draft?
			flash[:alert] = t("messages.course.add_to_cart.invalid")
			redirect_to root_path(subdomain: current_subdomain) and return
		end

		if user_signed_in? && @course.restrict? && !@course.array_of_allowed_emails.include?(current_user.email)
			flash[:alert] = t("messages.course.add_to_cart.restrict")
			redirect_to root_path(subdomain: current_subdomain) and return
		end

		if params[:coupon]
			@coupon = @course.coupons.active.find_by_name(params[:coupon])
			flash[:alert] = t("messages.course.add_to_cart.invalid_coupon") unless @coupon
		end

		@cart.cart_items.build course: @course, coupon: @coupon

		if @cart.save
	    Notification.create_list(
	    	sender: current_user, 
				receivers: current_school.team, 
				code: Notification::COURSE_ADD_TO_CART, 
				notifiable: @course
			) if current_school && current_user
			session[:cart_id] = @cart.id
			redirect_to cart_checkouts_path(subdomain: current_subdomain)
		end
	end

	def remove_from_cart
		@course = Course.find(params[:id])

		if @course && current_cart
			cart_item = CartItem.find_by_cart_id_and_course_id(current_cart.id, @course.id)
			cart_item.destroy if cart_item
			redirect_to cart_checkouts_path
		else
			redirect_to root_url, :alert => I18n.t("messages.course.remove_from_cart.failure")
		end
	end

	def add_coupon
		@course = Course.find(params[:id])
		@cart_item = CartItem.find(params[:cart_item_id])
		@coupon = @course.coupons.active.find_by_name(params[:coupon])

		if @coupon
			if @cart_item.update_attributes(coupon: @coupon)
				flash[:notice] = t("messages.course.add_coupon.success")
			else
				flash[:alert] = t("messages.course.add_coupon.failure")
			end
		else
			flash["invalid_coupon_#{@cart_item.id}"] = t("coupon.invalid")
		end

		redirect_to cart_checkouts_path
	end

	def remove_coupon
		@course = Course.find(params[:id])
		@cart_item = CartItem.find(params[:cart_item_id])
		@cart_item.update_attribute(:coupon_id, nil)
		flash[:notice] = t("messages.course.remove_coupon.success")
		redirect_to cart_checkouts_path		
	end	

	def request_certificate
		@course = Course.find(params[:id])

		begin
			Notification.create_list(
				sender: current_user, 
				receivers: @course.school.admins + @course.teachers, 
				notifiable: @course, 
				code: Notification::COURSE_NEW_CERTIFICATE_REQUEST
			)
			flash[:notice] = "Solicitação de certificado enviada com sucesso"
		rescue
			flash[:alert] = "Ocorreu um erro ao solicitar seu certificado"
		end

		redirect_to content_course_path(@course)
	end

	def affiliate
		@course = Course.find(params[:id])
		@coupon = @course.coupons.find_by_name(params[:coupon])

		unless @coupon
			flash[:alert] = "Cupom não encontrado."
			redirect_to root_path(subdomain: current_school.subdomain) and return
		end

		@cart_items = CartItem.with_purchase.with_price.where(coupon_id: @coupon.id).includes(:purchase).order("cart_items.created_at DESC")
		@cart_items_confirmed = @cart_items.payment_confirmed
		
		@billing_last_month = @cart_items_confirmed.between((Date.today - 1.month).beginning_of_month, (Date.today - 1.month).end_of_month).sum(&:price_with_discount)
    @billing_this_month = @cart_items_confirmed.between(Date.today.beginning_of_month, Date.today).sum(&:price_with_discount)

    @total_of_cart_items_confirmed = @cart_items_confirmed.length
    @total_of_cart_items_pending = @cart_items.pending.length
    @total_of_cart_items_canceled = @cart_items.canceled.length
    @total_of_cart_items_paid_with_billet = @cart_items_confirmed.paid_with_billet.length
    @total_of_cart_items_paid_with_online_debit = @cart_items_confirmed.paid_with_online_debit.length
    @total_of_cart_items_paid_with_credit_card = @cart_items_confirmed.paid_with_credit_card.length

		@cart_items = @cart_items.page(params[:page]).per(20)
	end

	private
	def use_https?
		unless current_school.try(:use_custom_domain) || request.host.include?("lvh.me") || Rails.env.staging?
			["add_coupon", "remove_coupon", "remove_from_cart", "checkout_free"].include?(params[:action])
		end
  end

end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
	before_filter :authenticate_user!
	layout :layout_dashboard

	private
	def layout_dashboard
		"dashboard/dashboard"
	end
end

app/controllers/dashboard/coupons_controller.rb
#coding: utf-8

class Dashboard::CouponsController < Dashboard::BaseController
  load_and_authorize_resource
  before_filter :set_course
  
  # def update
  #   @coupon = @course.coupons.find(params[:id])
  #   if @coupon.update_attributes(params[:coupon])
  #     flash[:notice] = t("messages.coupon.update.success")
  #     redirect_to dashboard_coupons_path
  #   else
  #     flash[:alert] = @coupon.errors.full_messages
  #     render :edit
  #   end
  # end

  def create
    @coupon = @course.coupons.new(params[:coupon])
    if @coupon.save
      flash[:notice] = t("messages.coupon.create.success")
      redirect_to edit_price_and_coupon_dashboard_course_path(@course)
    else
      render template: "dashboard/courses/edit_price_and_coupon", layout: "dashboard/course_edit"
    end
  end

  def destroy
    @coupon = @course.coupons.find(params[:id])
    @coupon.destroy
    flash[:notice] = t("messages.coupon.destroy.success")
    redirect_to edit_price_and_coupon_dashboard_course_path(@course.id)
  end

  private
  def set_course
    @course = Course.find(params[:course_id])
  end

end

app/controllers/dashboard/layout_configurations_controller.rb
#coding: utf-8

class Dashboard::LayoutConfigurationsController < Dashboard::BaseController	
	load_and_authorize_resource

	def index
		@user = current_user
		@school = @user.school
		@layout = @school.layout_configuration 
	end

	def update
		@layout = LayoutConfiguration.find(params[:id])

		if @layout.update_attributes(params[:layout_configuration])
			flash[:notice] = t('messages.layout.update.success')
			redirect_to dashboard_layout_configurations_path
		else
			flash[:alert] = t('messages.layout.update.failure')
			render :index
		end	
	end

end

app/helpers/courses_helper.rb
#coding: utf-8

module CoursesHelper

	def payment_status_message course_item
		case course_item.status
		when :within_validity
			"<i class=\"icon-facetime-video\"></i> Assistir Curso".html_safe
		when :pending
			"<i class=\"icon-time\"></i> Pagamento #{course_item.purchase.payment_status}".html_safe
		when :out_of_date
			"<i class=\"icon-ban-circle\"></i> Período terminado".html_safe
		end
	end

	def payment_status_path course_item
		case course_item.status
		when :within_validity
			content_course_path(course_item.course)
		when :pending
			purchases_user_path
		when :out_of_date
			course_path(course_item.course)
		end
	end

	def payment_status_availabity_message course_item
		case course_item.status
		when :within_validity
			if course_item.limited?
				"Disponível até #{I18n.l(course_item.expires_at, format: :medium)}"
			else
				"Disponível indeterminadamente"
			end
		when :pending
			"Pagamento #{course_item.purchase.payment_status}"
		when :out_of_date
			"Período terminado em #{I18n.l(course_item.expires_at, format: :medium)}"
		end
	end

end

app/views/dashboard/courses/_coupon_modal.html.erb
<%= content_for :modal do %>

<div id="newCoupon" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h2 id="myModalLabel"><i class="fa-icon-edit"></i> Novo Cupom</h2>
      </div>
      <%= simple_form_for @coupon || Coupon.new, :url => dashboard_course_coupons_path(@course) do |f| %>
        <div class="modal-body">
          <div class="row-fluid">
            <div class="span10">
              <%= f.input :name, label: "Nome", :placeholder => "Digite o nome do cupom" %></p>

              <%= f.input :discount, label: "Desconto (%)" %></p>

              <div class="input-group">
                <%= f.input :expiration_date, label: "Validade" %>
              </div>
              <br>

              <%= f.input :quantity, label: "Quantidade", :size => "4" %></p>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Fechar</button>
          <%= f.submit "Criar Cupom", :class => "btn btn-success", :id => "submit-course" %>
        </div>
      <% end -%>
    </div>
  </div>
</div>

<% end -%>

app/views/dashboard/courses/_course_box.html.erb
<div class="span4">
	<div class="course-item" id="course-<%= course.slug %>">
		<div class="pagination-centered">
			<div class="img-container">
				<div class="info-edit">
					<%= link_to dashboard_course_path(course), class: "btn btn-inverse" do %>
						<i class="icon-edit"></i> Gerenciar curso
					<% end %>
				</div>
				<%= link_to image_tag(course.logo.url(:medium)), dashboard_course_path(course.id), :class => "course-logo" %>
			</div>
		</div>
		<div class="info-show">
			<h4><%= course.title_short %></h4>
			<h5 class="muted"><%= course.published? ? "Publicado" : "Rascunho" %></h5>
		</div>
	</div>
</div>

app/views/dashboard/courses/course_categories.html.erb
<%= render_widget :course_categories, :display %>

app/views/dashboard/courses/edit_certificate.html.erb
<%= box(title: "Certificado") do %>
	<%= simple_form_for @course, :url => dashboard_course_path(@course, edit_action: :edit_certificate) do |f| %>
		<div class="row-fluid">
			<label class="radiobutton inline span2">
				<%= f.radio_button :certificate_available, true, :class => "btn" %> Sim
			</label>
			<label class="radiobutton inline span2">
				<%= f.radio_button :certificate_available, false, :class => "btn" %> Não
			</label>
		</div>
		<br>

		<div class="row-fluid">
			<div class="span1">
				<i class="fa-icon-question-sign"></i>
			</div>
			<div class="span8">
				<p class="muted">
					Caso o seu curso ofereça certificado um botão para solicitá-lo será exibido na área aonde o aluno consome o conteúdo do curso.
				</p>
			</div>
		</div>
		<div class="form-actions"> 
			<%= f.submit "Salvar", :class => "btn btn-success" %>
		</div>
	<% end -%>
<% end %>

app/views/dashboard/courses/edit_detailed_info.html.erb
<div class="box_widget_course">
	<div class="box">
		<div class="head">
			<h4>Informações Detalhadas</h4>
		</div>
		<div class="content">
			<fieldset>
				<%= simple_form_for @course, :url => dashboard_course_path(@course, edit_action: :edit_detailed_info) do |f| %>
					<div class="row-fluid">
						<div class="span6">
							<%= f.input :description, as: :text, label: "Descrição do curso (?)", label_html: { class: 'hint hint--large', :data => {:hint => "Esta é a sua chance de deixar o mundo saber sobre seu curso, como o aprendizado é estruturado e tudo o que mais for interessante. Você também deve incluir alguns detalhes, como o tipo de material encontrado no curso e quanto tempo vai demorar para concluir o curso." }}, input_html: { :class => "tinymce span9", :size => "100x25", style: "height: 200px;"} %>
							<br />
							<hr>
							<%= f.input :content_and_goals, as: :text, label: "O que o aluno aprenderá com o curso (?)", label_html: { class: 'hint hint--large', :data => {:hint => "Ressalte o que o aluno ganhará de conhecimento ao fazer o curso. Ex: Nesse curso você aprenderá como tomar o controle da sua vida financeira, como planejar seu futuro e  - acima de tudo - como colocar o dinheiro para trabalhar para você." }}, input_html: { :class => "tinymce span9", :size => "100x5", style: "height: 200px;"}%>
							<br />
							<hr>	
							<%= f.input :who_should_attend, as: :text, input_html: { :class => 'tinymce span9', :size => "100x2", style: "height: 200px;"}, :placeholder => "Ex.: Pessoas interessadas em adquirir sua independência financeira trabalhando de casa", label: "Público-alvo (quem deve comprar esse curso?)" %>
						</div>
						<div class="span6">
							<%= f.input :testimonials, label: "Depoimentos dos alunos (?)", as: :text, label_html: { class: 'hint hint--large', :data => {:hint => "Destaque os depoimentos dos alunos apaixonados pelo curso e mostre para os potenciais alunos como seu curso é bom." }}, input_html: { :class => "tinymce span9", :size => "100x20", style: "height: 200px;"}, :placeholder => "Adicione aqui os depoimentos dos seus alunos mais apaixonados." %>
							<br>
							<hr>
							<%= f.input :advantages, as: :text, input_html: { :class => 'tinymce span9', :size => "100x2", style: "height: 200px;"}, :placeholder => "Ex.: Ao comprar esse curso você ganhará acesso ao nosso forum especial.", label: "Vantagens ao comprar esse curso" %>
						</div>
					</div>
					<br />
					<hr>	
		    	<div class="form-actions">
			    	<%= f.submit "Salvar", :class => "btn btn-success" %>
			  	</div>
				<% end -%>
			</fieldset>
		</div>
	</div>
</div>
<%= tinymce_assets %>
<%= tinymce %>

app/views/dashboard/courses/edit_image.html.erb
<div class="box_widget_course">
	<div class="box">
		<div class="head">
			<h4>Imagem do curso</h4>
		</div>
		<div class="content">
			<fieldset class="pagination-centered">
				<% if @course.logo %>
					<h3>Atual:</h3>
					<%= image_tag @course.logo.url(:large), :class => "img-polaroid" %>
				<% end -%>

				<br>
				<br>

				<div class="row-fluid">
					<i class="icon-exclamation-sign"></i> <strong>Importante:</strong> Tamanho ideal: <strong>500x280</strong> (Propoção 16 por 9).</p>

					<hr>
					<div class="span4 offset4">
						<%= simple_form_for @course, :url => dashboard_course_path(@course, edit_action: :edit_image) do |f| %>
					    <%= f.input :logo, label: "Imagem" %>
					    <br>
					    <%= f.submit "Salvar", :class => "btn btn-success" %>
						<% end -%>
					</div>
				</row-fluid>

			</fieldset>
		</div>
	</div>
</div>

app/views/dashboard/courses/edit_instructor.html.erb
<%= box(title: "Instrutor") do %>
	<fieldset>
		<%= simple_form_for @course, :url => dashboard_course_path(@course, edit_action: :edit_instructor) do |f| %>	
      <%= f.input :instructor_bio, label: "Biografia do instructor", as: :text, :size => "1000x3", input_html: { :class => "tinymce span9" }, :placeholder => "Adicione aqui informações do instrutor do curso." %></p>

    	<div class="form-actions">
	    	<%= f.submit "Salvar", :class => "btn btn-success" %>
	  	</div>
		<% end -%>
	</fieldset>
<% end %>

<%= tinymce_assets %>
<%= tinymce %>

app/views/dashboard/courses/edit_price_and_coupon.html.erb
<%= render "dashboard/courses/coupon_modal" %>

<div class="box_widget_course">
	<div class="box">
		<div class="head">
			<h4>Preço e cupons</h4>
		</div>
		<div class="content">
			<%= simple_form_for @course, :url => dashboard_course_path(@course, edit_action: :edit_price_and_coupon) do |f| %>
				<h2>Preço do Curso</h2>
				<hr>
		    <%= f.input :price, as: :string %>
				<p class="muted">O curso deve ter preço mínimo de R$ 30,00.</p>

				<br>
	
			  <h2>Cupons</h2>
			  <hr>
		    <%= link_to "Novo Cupom +", '#newCoupon', :class => "btn btn-success", :id => "new-coupon", "role" => "button", "data-toggle" => "modal" %>
		    <br>
		    <br>
			  <table class="table table-striped table-hover" id="tabela_atendimentos">
			    <thead>
			      <tr>
			        <th>Nome</th>
			        <th>Desconto</th>
			        <th>Validade</th>
			        <th>Quantidade</th>
			        <th>Restante</th>
			        <th>Links para divulgação</th>
			      </tr>
			    </thead>
			    <tbody>
			      <% @course.coupons.not_automatic.each do |coupon| %>
			      <tr>
			        <td><%= coupon.name %></td>
			        <td><%= "#{coupon.discount}%" %></td>
			        <td><%= l coupon.expiration_date, format: :long %></td>
			        <td><%= coupon.quantity %></td>
			        <td><%= coupon.quantity_left %></td>
			        <td>
			        	<%= link_to "<i class='icon-facetime-video'></i>".html_safe, course_path(@course, coupon: coupon.name), class: "hint hint--left btn-small", "data-hint" => "Para a página do curso com o cupom aplicado", "target" => "_blank" %>
			        	<%= link_to "<i class='fontello-icon-basket'></i>".html_safe, add_to_cart_course_path(@course, coupon: coupon.name), class: "hint hint--left btn-small", "data-hint" => "Direto para o carrinho com o cupom aplicado", "target" => "_blank" %>
			        	<%= link_to "<i class='fontello-icon-chart-line'></i>".html_safe, affiliate_course_path(@course, coupon.name), class: "btn-small hint hint--left", "data-hint" => "Relatório de vendas do cupom", "target" => "_blank" %>
			        </td>
			        <% unless coupon.new_record? %>
				        <td class="item_center">
				          <%= link_to "<i class='fontello-icon-trash'></i>".html_safe, dashboard_course_coupon_path(@course, coupon), :method => :delete, :confirm => "Apagar cupom?", :class => "btn btn-danger btn-mini", id: "delete-coupon-#{coupon.id}" %>
				        </td>
			        <% end %>
			      </tr>
			      <% end %>
			    </tbody>
			  </table>

				<div class="form-actions">
				  <%= f.submit "Salvar", :class => "btn btn-success" %>
				</div>

			<% end -%>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		if(window.location.pathname.indexOf("/coupons") !== -1) {
			$("#newCoupon").modal('show');
		}
	});
</script>

app/views/dashboard/courses/library.html.erb
<%= render_widget :school_library, :display, school: @school %>